### ISSUE TITLE
Weird characters on mouse click when SSH connection is broken

### ISSUE THREAD

**Issue by tnguyen14** [junegunn/fzf#1502] opened 2019-02-12 15:29 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I ssh into a remote linux machine with fzf set up (I have `source ~/.fzf.bash` in my `.bashrc`), when the connection becomes disconnected and I'm back to my host's shell, on every mouse click, I get weird characters printed on the screen, like `0;86;60M0;86;60m`.

I am guessing this is due to the `key-bindings.bash` file, but not sure.

**Comment by junegunn** [comment] 2019-02-14 09:44
I have no idea what's going on there. `reset` command may fix the case.

**Comment by tnguyen14** [comment] 2019-02-14 12:47
Yes `reset` is my current workaround. I was wondering if there's a way I could try and debug this further?

**Comment by junegunn** [comment] 2019-02-15 01:07
Are you saying that it only happens on exceptional cases where SSH connection is accidentally disconnected? Does it happen even when you never run fzf on the remote connection?

**Comment by tnguyen14** [comment] 2019-02-21 20:55
@junegunn Yes to both of those questions. If I have an existing SSH session at work, and disconnect from the VPN when I leave work, it will happen. It doesn't happen if I run `exit` to close the SSH connection.

And it happens without running `fzf`, just sourcing the bash file.

**Comment by junegunn** [comment] 2019-02-22 01:10
> And it happens without running `fzf`, just sourcing the bash file.

Then I'm certain that it's not related to fzf. I'm closing this but please let me know if you have good reason to believe that it's caused by fzf scripts.

**Closed by junegunn** 2019-02-22 01:10 UTC

**Comment by tnguyen14** [comment] 2019-02-22 14:55
Even without running fzf, I could confirm that the issue occurs because of sourcing `.fzf.bash`, which sources `key-bindings.bash`, which is a part of this repo, right?

**Comment by junegunn** [comment] 2019-02-23 06:08
> I could confirm that the issue occurs because of sourcing `.fzf.bash`

How did you confirm that? Which line of the source code causes the problem? Since there is no way I can reproduce the problem, I cannot help you investigating the problem.

**Comment by junegunn** [comment] 2019-02-23 06:23
And to my understanding, there is no code in the scripts that might affect the state of the terminal.

```sh
$ /bin/bash --norc

bash-3.2$ stty -g; source ~/.fzf.bash; stty -g
gfmt1:cflag=4b00:iflag=6902:lflag=5cb:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=9600:ospeed=9600
gfmt1:cflag=4b00:iflag=6902:lflag=5cb:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=9600:ospeed=9600
bash-3.2$
```

**Comment by tnguyen14** [comment] 2019-02-25 19:54
> How did you confirm that?

I tried to reproduce it over the courses of a few days. Commenting our soucing of `.fzf.bash` was the sure way to reproduce the problem.

> there is no code in the scripts that might affect the state of the terminal

Is there any chance to key bindings script change the character sequence being sent to the terminal somehow? I don't know enough here, just a guess on my part.
