### ISSUE TITLE
Different behavior for a key binding in different popups?

### ISSUE THREAD

**Issue by JJPandari** [junegunn/fzf#1658] opened 2019-08-05 08:10 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

### requirement

Ability to bind the same key to different behaviors depending on the pop:  

- when I `enter` in the history popup/widget, fzf quits the popup and executes the selected command.
- when I `enter` in the `ctrl-t`(file select) popup, fzf does the default: quit the popup and paste the current selection to cli.

### possible solution

In `fzf-history-widget` or so, set a variable indicating what the current popup is, so I can do things conditionally when `fzf --bind`. Something like (not tested yet):  

```sh
my-fzf-history-widget() {
  export FZF_POPUP_TYPE='history'
  fzf-history-widget()
}
zle     -N   my-fzf-history-widget
bindkey '^R' my-fzf-history-widget
```

Is there any better way? How about add the `FZF_POPUP_TYPE` to fzf itself?

**Comment by junegunn** [comment] 2019-08-06 04:50
Duplicate of #1492

**Closed by junegunn** 2019-08-06 04:50 UTC
