### ISSUE TITLE
^R broken when installed with homebrew

### ISSUE THREAD

**Issue by casimir** [junegunn/fzf#175] opened 2015-03-31 18:10 UTC
It's kind of a edge case. I'm using the homebrew version of fzf (which is an _old_ version):
```
$ fzf --version
0.9.4
```
Here is the thing, I use config files from the repo directly with `bundle https://github.com/junegunn/fzf shell`. When using ^R I have this message `unknown option: --toggle-sort=ctrl-r`. This option seems to have been introduced with #173.

The best solution for me would be to update the homebrew package. Have you some workflow to update homebrew version? Note that I have the same problem with the [aur package](https://aur.archlinux.org/packages/fzf/) on Archlinux.

I would be glad to help if you need, I have become quite dependant to fzf.

**Comment by junegunn** [comment] 2015-04-01 00:44
I'm planning to release a new homebrew version when #137 is closed because I do not want to push another patch version later (0.9.7-1) just because of the change in the vim plugin part of the repo. But it's getting delayed as with the progress of neovim itself. Is there any reason you need to separately use binary from homebrew, and extension code from the tip of the repo? I can't always guarantee that they are compatible across commit history.

**Comment by junegunn** [comment] 2015-04-01 12:48
Okay, I'll push a new version, but I'll enable `--HEAD` option as well so that the users can install the latest version using Homebrew.

```sh
# To install the latest version
brew reinstall fzf --HEAD

# Install shell extensions - this should be done whenever fzf is updated
/usr/local/Cellar/fzf/HEAD/install
```

**Comment by junegunn** [comment] 2015-04-01 13:00
https://github.com/Homebrew/homebrew/pull/38270

**Comment by casimir** [comment] 2015-04-01 13:02
Maybe this is a perversion of using tools working in the "all on Github today" way (antigen, vim-plug, ...) I'm using several machines and OSes daily so I try to keep my `.zshrc` as small as possible, counting on internet for the rest. Since a lot of projects I use keep the _master_ branch usable it works quite well.

Is the Go version in the same state? I systematically have Go set up on my machine so has a workaround I use `go get github.com/junegunn/fzf/src/fzf`. It seems to work well.

By curiosity why don't you want to release several patches? Some automated systems just used git tags (releases if you "talk Github").

Last thing thank you very much for vim-plug and fzf. It just work and that's a breeze after spending so much time searching for THE tool, but finding only incomplete or buggy ones.

**Comment by casimir** [comment] 2015-04-01 13:09
Hum too late... Thank you though! I'm still interested if you have some minutes to answer my questions in the previous comment.

**Comment by junegunn** [comment] 2015-04-01 15:19
> Is the Go version in the same state?

I had to keep the master branch stable when fzf was developed in Ruby. But now fzf is mainly in Go and distributed as a compiled binary, I don't have to. And that is kind of relieving to me. But I still do not push an incomplete or unstable set of commits to the master branch at least not intentionally. However, there's no guarantee at all on the backward compatibility of a new experimental feature pushed to master until it's officially released. I may decide to change its specification, or even decide not to have it.

> I use go get github.com/junegunn/fzf/src/fzf. It seems to work well.

Once the above PR to Homebrew is merged, `brew reinstall fzf --HEAD` will build a new binary from the latest source. No need to set up Go environment.

> By curiosity why don't you want to release several patches?

Well, it's basically a personal preference and there are some practical reasons as well. I do not prefer softwares that release new versions *too often*. For a user, updates can be bothersome. And although frequent releases can be a sign of active development, on the other hand, it can give the impression that the software is unstable and has to be fixed constantly (right or wrong).

Sending pull request to Homebrew is the extra work that I have to do, that I don't like to do. And there is [code in install script for fish](https://github.com/junegunn/fzf/blob/master/install#L212) that I'm particularly concerned about that prepends the path of fzf to a persistent global variable. It's okay when the user manually cloned fzf repository to a fixed path (e.g. `~/.fzf`) But different versions of fzf installed with Homebrew will have different paths, and if a fish user keeps running the install script every time fzf is updated, the variable will have paths that are no longer used. There should be a better way to handle this, but I know little about fish and do not care much about it, I didn't look further into it. Once the PR is merged, I'll update the README to promote the use of `--HEAD` option so that the path is fixed to `/usr/local/Cellar/fzf/HEAD`.

> Last thing thank you very much for vim-plug and fzf.

Thanks :) I'll let you know when the new version is ready on Homebrew.

**Comment by casimir** [comment] 2015-04-01 22:24
Interesting answers thanks.

About your `$PATH` problem, just a quick thinking without looking at the script, what you see in a lot of packages for UNIX are symbolic links, they have less side effect than changing `$PATH`. Most homebrew packages use this to put binaries in the system wide bin directory ([e.g. for Go](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/go.rb#L89)). On most Linux distributions it is used to handle several version of libraries or runtimes (Java is a good example) without bothering the user.

So summarized symbolic links are nice for 2 things:
* handling several version transparently without `$PATH` modification: `/usr/bin/fzf -> /usr/local/Cellar/fzf/0.9.1/bin/fzf` vs `/usr/bin/fzf -> /usr/local/Cellar/fzf/0.10.0/bin/fzf`
* simplify versionning: `/usr/lib/libc.so -> /usr/lib/libc.6.so -> /usr/lib/libc.6.17.so`

Everyday example (for me at least), in a shell `gcc` resolves to the most up-to-date version and `gcc-4.8` resolves to the 4.8 version. Both are in fact symbolic links in `/usr/bin`.

If you want more details I'd glad to help you.

**Comment by junegunn** [comment] 2015-04-01 23:08
I don't want to require root previlege and touch system-wide bin directories for installing fzf. So that's why it was designed to modify the user's `$PATH`.

**Comment by junegunn** [comment] 2015-04-02 16:23
The PR is now merged and I updated the README page accordingly.

**Closed** 2015-04-02 16:22 UTC

**Comment by casimir** [comment] 2015-04-03 11:17
It works perfectly now. Just one last thing before I stop annoying you, with a normal homebrew install /usr/local/bin is owned by the user so you don't actually need root privileges. Anyway thank you for your time.

**Comment by junegunn** [comment] 2015-04-03 13:10
Yeah, I know, but you do need root privilege when you first install homebrew itself. :) Well, talking about root privilege on OS X is pointless anyway as Macs are usually personal computers.
