### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by ateric** [junegunn/fzf#3690] opened 2024-03-21 16:42 UTC
```
Name Id           Version Source
--------------------------------
fzf  junegunn.fzf 0.48.1  winget
```
![image](https://github.com/junegunn/fzf/assets/28189649/b9bd02d6-a205-4e9f-9ffc-d0ab2efce225)

**Comment by AddictArts** [comment] 2024-03-21 18:30
I wonder if this is a false positive? I had the same happen. Downloaded the latest from here,, releases. Placed the exe in AppData\Local\Microsoft\Winget\ ... and scanned again using the context menu "Scan with ...". Zero threats found, so the winget manifest must be compromised and where that is hosted and cached. Meaning the issue is not here? fyi.

**Comment by hahv** [comment] 2024-03-22 01:38
version 0.48.0 does not get this one (scanned with MS Window Defender)

**Comment by junegunn** [comment] 2024-03-22 02:14
Must be a false positive. This has happened multiple times in the past.

3174

**Comment by aniketgm** [comment] 2024-03-22 08:55
@ateric Try fzf from scoop. I'm not getting the error you mentioned.
`~\AppData\Local\Microsoft\Winget\....` seems to be a critical area for Windows apps. So maybe that's why windows is complaining.

**Comment by junegunn** [comment] 2024-04-07 00:58
Closing as this is a false positive and we have a new release.

**Closed by junegunn** 2024-04-07 00:58 UTC
Labels: windows
