### ISSUE TITLE
Binary release for Linux ARM (Raspberry Pi 2)

### ISSUE THREAD

**Issue by knopki** [junegunn/fzf#685] opened 2016-10-01 15:12 UTC
- Category
  - [x] fzf binary
- OS
  - [x] Linux

It would be great to have binary release for linux arm.

I have Raspberry Pi 2 with OSMC installed (Debian 8.6).

```
osmc@osmc:~$ uname -a
Linux osmc 4.4.13-5-osmc #1 SMP PREEMPT Mon Jun 20 16:34:27 UTC 2016 armv7l GNU/Linux
```

Current android_arm7 binary doesn't work: 

```
osmc@osmc:~$ file fzf-0.15.3-android_arm7 
fzf-0.15.3-android_arm7: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
osmc@osmc:~$ ./fzf-0.15.3-android_arm7 
bash: ./fzf-0.15.3-android_arm7: No such file or directory
```

I can build fzf with git clone && ./install. Resulting binary working great:

```
osmc@osmc:~$ file .local/bin/fzf
.local/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=08782330f13969d81eda473893d991967fedc962, not stripped
osmc@osmc:~$ ldd .local/bin/fzf
    linux-vdso.so.1 (0x7ef85000)
    /usr/lib/libarmmem.so (0x76fb5000)
    libncurses.so.5 => /lib/arm-linux-gnueabihf/libncurses.so.5 (0x76f86000)
    libtinfo.so.5 => /lib/arm-linux-gnueabihf/libtinfo.so.5 (0x76f5b000)
    libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f38000)
    libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76e48000)
    libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76e35000)
    /lib/ld-linux-armhf.so.3 (0x54b39000)
osmc@osmc:~$ fzf --version
0.15.3
```

**Comment by junegunn** [comment] 2016-10-01 16:51
Ping @acornejo

**Comment by acornejo** [comment] 2016-10-14 16:15
Sorry for the late reply. This is easily fixed. The root problem is that android uses a non standard libc (and lacks glibc).

Thus, we need two arm builds, one for vanilla arm Linux like Raspbian, and another for Android arm linux. I'll see if I can fiddle with the docker files over the weekend to get another arm build.

**Comment by acornejo** [comment] 2016-10-14 16:19
Forgot to mention, this bug seems a duplicate of #465.

**Comment by junegunn** [comment] 2017-01-22 09:37
Hi, can you guys check if the arm7 alpha binary on the below link works on the platform?

https://github.com/junegunn/fzf-bin/releases/alpha

**Comment by junegunn** [comment] 2017-01-23 15:51
https://github.com/junegunn/fzf-bin/releases/0.16.2

**Closed by junegunn** 2017-01-23 15:51 UTC

**Comment by knopki** [comment] 2017-01-23 23:00
arm7 binary works on rpi2 (armv7l) without any problems. Thank you! :+1:
