### ISSUE TITLE
List displaying is broken in tmux

### ISSUE THREAD

**Issue by lazywei** [junegunn/fzf#190] opened 2015-04-15 08:54 UTC
Hi, I'm not sure if this is a bug in fzf or tmux. I got the "broken" list when using fzf under tmux.
Everything just works fine when outside tmux.
Thanks.
![image](https://cloud.githubusercontent.com/assets/2840571/7155270/ee8001ea-e38f-11e4-8c6f-5989b14ebfd1.png)

**Comment by edi9999** [comment] 2015-04-15 09:52
I had the same issue.

The problem is easily solved : See https://github.com/junegunn/fzf#rendering-issues

Specifically: If you're on screen or tmux, $TERM should be either screen or screen-256color

**Comment by junegunn** [comment] 2015-04-15 10:06
Yeah, I'm pretty sure that this is a duplicate of #176.

**Comment by lazywei** [comment] 2015-04-15 10:16
Okay, thank you both. I'll check it out!



-- Chih-Wei

**Closed** 2015-04-15 10:30 UTC
