### ISSUE TITLE
Tab completion prints error when command starts with backslash

### ISSUE THREAD

**Issue by kbd** [junegunn/fzf#1975] opened 2020-04-12 13:44 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have `cat` aliased to `bat`. I wanted to use regular `cat` recently, so I typed:

```shell
$ \cat file[tab]
fzf-completion:26: parse error: condition expected: =
$ \cat file.txt
```

It doesn't break zsh's autocompletion, but prints the error. Plain `cat` without the backslash gives no error.

**Comment by junegunn** [comment] 2020-04-12 14:36
Thanks, this is a duplicate of #1973.

**Closed by junegunn** 2020-04-12 14:36 UTC
