### ISSUE TITLE
--select-1 without a query

### ISSUE THREAD

**Issue by octotep** [junegunn/fzf#459] opened 2015-12-29 04:42 UTC
Would it be possible to allow for `fzf` to autoselect a single search result interactively?

For example:
```echo -e "This\nis\n\a\ntest" | fzf --query=a -1```
will autoselect "a"

What I would like is something more along the lines of:
```echo -e "This\nis\na\ntest" | fzf -1```
and after entering "a", `fzf` would autoselect the result without the need to hit enter

**Comment by junegunn** [comment] 2015-12-29 06:08
`--select-1` can be used without `--query` as follows:

```sh
> echo "This" | fzf -1
This
```
However, it does not auto-select a match while interactively narrowing down the list. It is by design, and I don't think I prefer the suggested behavior as it can be confusing especially when you accidentally type in a wrong character. You don't get a chance to correct the query and you never know if you selected the right entry or not. But maybe that's just me, and I don't know whether if it's a common requirement as you're the first one to have suggested it.

**Comment by octotep** [comment] 2016-01-01 16:34
Sorry for the late reply. After some thought, I agree with you. It seems like it would introduce a very confusing behavior for end users, and I'm not sure how valuable interactive autoselect would be in the end.
Feel free to close this issue if you think it's appropriate

**Comment by junegunn** [comment] 2016-01-01 17:53
Thanks for the feedback. Let me mark this issue `wontfix`.

**Closed by junegunn** 2016-01-01 17:53 UTC

**Comment by pbartyik** [comment] 2020-07-21 06:28
I could use this for quick tmux window switching (I use connected hostnames as window names). Could this be implemented as a separate function, for example `--interactive-select-1` and `--interactive-exit-0`?

**Comment by Zik42** [comment] 2020-10-28 22:10
> I could use this for quick tmux window switching (I use connected hostnames as window names). Could this be implemented as a separate function, for example `--interactive-select-1` and `--interactive-exit-0`?

Have you found some other solution? Maybe some fork?

**Comment by pbartyik** [comment] 2020-10-29 04:15
unfortunately no :( if you findsomething do let me know please

**Comment by Zik42** [comment] 2020-10-29 06:49
@pbartyik I tried to do smth with native api of fzf, but I cant figure out how to make it work and dont shure it is the fastest way... I did smth like ( pseudo code ):
fzf --bind:change:execute  stdin | fzf -f {q} if len > 1 accept
I cant find any good placeholder to make it shorter. I need smth like filtered text placeholder. And I dont know how to call "accept" in  "execute" action. Maybe you are smarter ;) 
Dont want to fork to change source ...

**Comment by AvidSeeker** [comment] 2023-03-19 21:01
+1 for this feature.

Can't see how having one less keystroke (enter) goes against the idea of fuzzy matching.

**Comment by Andrej-Marsic** [comment] 2023-11-25 00:03
In case you got to here, from the commit above you can see that the way to do this is with
`fzf --bind one:accept`

**Comment by Zik42** [comment] 2024-02-13 08:00
> In case you got to here, from the commit above you can see that the way to do this is with `fzf --bind one:accept`

I waited for 3 years :D
