### ISSUE TITLE
Garbage escape symbols in preview window

### ISSUE THREAD

**Issue by eugene-babichenko** [junegunn/fzf#3867] opened 2024-06-15 22:12 UTC
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

When I run fzf with preview, it show some garbage that looks like escape symbols in the preview window.

`fzf --preview 'cat {}'`:

<img width="1728" alt="Screenshot 2024-06-16 at 01 09 56" src="https://github.com/junegunn/fzf/assets/15912853/05556070-80ae-4148-8a99-0153592dd73e">

**Comment by junegunn** [comment] 2024-06-16 00:25
Duplicate of https://github.com/junegunn/fzf/issues/1415

**Closed by junegunn** 2024-06-16 00:25 UTC
