### ISSUE TITLE
nvim window height for fzf#run is not enough for 2 options

### ISSUE THREAD

**Issue by ipwnponies** [junegunn/fzf#1535] opened 2019-03-23 21:50 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

# Summary
When calling `fzf#run` with 2 results, the fzf window is not sufficiently tall to display any results.

# Repro

## Setup
minimal_vimrc:
```
set nocompatible
call plug#begin('~/.vim/bundle')
    Plug 'junegunn/fzf', { 'dir': '~/.local/share/fzf', 'do': './install --all' }
call plug#end()
```

Command:
```vim
$ nvim -u minimal_vimrc
:call fzf#run({'source': ['oh hi', 'oh bye'], 'down': '~40%'})
```

I don't know what 'down' option does, it's provided by default from `fzf#wrap`.
https://github.com/junegunn/fzf/blob/315e568de006e80138f79c77d5508c7e4853e6b2/plugin/fzf.vim#L302-L308
It's how [LanguageClient-neovim is using it](https://github.com/autozimu/LanguageClient-neovim/blob/26c8727d61aa2b843b89ae2c7e89c830cd910b46/autoload/LanguageClient.vim#L207-L211), for additional context on use case.

### minimal_vimrc
Works for vim8 (8.0.1453)
![image](https://user-images.githubusercontent.com/4278368/54871948-a5d39800-4d79-11e9-9a40-af10a3535b70.png)
Broken in nvim (v0.3.1)
![image](https://user-images.githubusercontent.com/4278368/54871960-d3204600-4d79-11e9-9583-76b476428079.png)

### Using actual vimrc
I think this may provide clues. It looks like a padding issue, need more to account for neovim terminal mode?
vim 
![image](https://user-images.githubusercontent.com/4278368/54871996-7b360f00-4d7a-11e9-9e82-034ff1e01dcc.png)
neovim
![image](https://user-images.githubusercontent.com/4278368/54871994-6e192000-4d7a-11e9-84ae-f7af6b69c254.png)

**Comment by junegunn** [comment] 2019-03-26 07:46
Looks like you have `--border` in your FZF_DEFAULTS_OPTS. That has not been not correctly handled by Vim wrapper, so the problem is also reproducible on Vim if we force it to use a terminal buffer by using layout option other than `down`.

```vim
:let $FZF_DEFAULT_OPTS = ''
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--no-border --no-inline-info'})
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--inline-info'})
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--border'})
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--inline-info --border'})
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--inline-info --border --header foo'})
:call fzf#run({'source': range(2), 'up': '~40%', 'options': '--inline-info --border'})
```

 The above patch (in devel branch, soon to be merged to master) should help.

**Comment by ipwnponies** [comment] 2019-03-26 15:43
Oh nice, I forgot to mention the env var:
```sh
FZF_DEFAULTS_OPTS = --reverse --select-1 --exit-0 --border --height 40%  --min-height 10 --margin 1,5 --inline-info --bind pgdn:preview-page-down,pgup:preview-page-up,change:top,ctrl-s:toggle-sort
```
I've tested your repro and and can confirm it only occurs when both `--inline-info` and `--border` are set.

**Closed** 2019-03-31 02:28 UTC
Labels: bug
