### ISSUE TITLE
Fzf keybindings need two keystrokes before activating in neovim's terminal

### ISSUE THREAD

**Issue by andsild** [junegunn/fzf#1233] opened 2018-03-03 14:22 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

In neovim's terminal, I have to enter two keystrokes before fzf shows completions. Doesn't matter which keystrokes I enter, but there has to be two. 

Running fzf with e.g. `history | fzf` works normally. Its just the keybindings that are acting weird.

This affects zsh, bash and fish. I've tried with multiple terminals and operating systems (ubuntu/nixos).

## Reproduce
1. Open up neovim
2. execute `:term:`
3. Hit an fzf shortcut, e.g. `<c-r>` in the terminal. Suggestions won't come up until after you press two keystrokes.

## Info
```bash
:fzf --version
0.17.3 (390b496)

:cd ~/.fzf && git pull origin master && git status ~/.fzf/
From https://github.com/junegunn/fzf
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Current branch master is up to date.
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by junegunn** [comment] 2018-03-04 04:53
Thanks for the report but it's a duplicate of #809.

**Closed by junegunn** 2018-03-04 04:53 UTC

**Comment by andsild** [comment] 2018-03-04 11:43
Thanks for the redirect, sorry for wasting time
