### ISSUE TITLE
HOME and END stop working after using fzf

### ISSUE THREAD

**Issue by strokirk** [junegunn/fzf#279] opened 2015-06-24 08:58 UTC
Like the title says, <kbd>HOME</kbd> and <kbd>END</kbd> keys stop working for me after I've started and exited `fzf`. 

This only happens for one command, though, so after I abort or perform the command, <kbd>HOME</kbd> and <kbd>END</kbd> start working again.

I'm on Ubuntu 14.10 with fzf 0.9.13. This happens for me in the terminals Sakura, and Gnome terminal, but *not* in Terminator.

**Comment by junegunn** [comment] 2015-06-25 16:15
I don't have a linux desktop environment so I can't be of help on this at the moment. Maybe if you could provide a Vagrantfile or something for the environment, that would be helpful. Anyway I wonder if other users also experience the problem.

**Comment by edi9999** [comment] 2015-06-25 20:52
Nope, never seen anything like this

**Comment by strokirk** [comment] 2015-07-02 13:15
Some additional clarificaiton: I'm using Zsh, and <kbd>HOME</kbd> produces `\eOH` before invoking `fzf`, and `\e[H` afterwards. I just tested in Bash, and I can't reproduce the error there. Might be something in my Zsh config.

**Comment by jfchevrette** [comment] 2016-04-05 12:27
I am having the same issue but I'm running fzf on OS X (10.11.4) under iTerm (2/3 tried both). I'm also running zsh.

**Comment by guiniol** [comment] 2016-05-04 07:59
I have a probably related issue: `HOME`, `END` and all the `F*` keys do not work and insert a `~` instead. The problem doesn't persist after exiting fzf though. I'm using zsh and urxvt.

**Comment by junegunn** [comment] 2016-05-04 17:43
Hmm, I still can find a way to reproduce the problem. Note that it's normal that the function keys from F5 give `~` as they are currently not supported. And as a workaround you can use CTRL-A and CTRL-E instead of HOME and END.

**Comment by guiniol** [comment] 2016-05-04 18:00
Ok. So `HOME` and `END` are supposed to be supported?

**Comment by junegunn** [comment] 2016-05-05 10:22
Yeah, I use OS X and they work in iTerm2, Terminal.app and Neovim terminal buffer. But I just confirmed that they don't work correctly in urxvt as you reported. I'll look into it when I get some time, but I don't use urxvt, so any help is appreciated. A quick googling points me to the following link, might be relevant:
https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#URxvt.2FRxvt

**Comment by guiniol** [comment] 2016-05-05 16:13
@junegunn Thanks for the link. This fixed it. Not sure why I've never seen that in any other application though ^^. Sorry for the noise.

**Comment by guiniol** [comment] 2016-06-29 20:04
Quick update: the fix @junegunn gave me made `HOME` and `END` work in `fzf` but now they don't work in `neovim`.
I added a comment at the end of this issue: neovim/neovim#4308

Basically, if I add to Xdefaults:
```
urxvt*keysym.Home: \033[1~
urxvt*keysym.End: \033[4~
urxvt*keysym.KP_Home: \033[1~
urxvt*keysym.KP_End:  \033[4~
```

then `HOME` and `END` work in fzf but not in neovim, and if I remove that, it works in neovim but not in fzf. In both cases, both neovim and fzf work in tmux.
So I'm at a loss as to how to debug that. Any tips would be appreciated.

**Comment by justinmk** [comment] 2016-06-29 20:37
@guiniol Did you also do the terminfo steps at  https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#URxvt.2FRxvt ?

If Xdefaults is sending sequences that don't match terminfo, neovim (and other apps that respect terminfo) won't interpret them correctly.

**Comment by guiniol** [comment] 2016-06-29 21:26
That fixed it, thanks.
I don't understand why urxvt would do something so not default, and how this issue has never arisen in all the years I've been using it.

**Comment by guiniol** [comment] 2016-06-29 22:13
Reading https://github.com/junegunn/fzf/blob/3e1d6a7bcf2a47a494d602389fda415d8fad8e03/src/curses/curses.go#L495 it seems that fzf is not reading the terminfo and assuming the values for the various escape codes. It would be better to read these values from the terminfo. I have no idea if that's a lot of work, or if there is a library or anything. If this issue is still there when I get around to it, I'll take a look.

**Comment by eigengrau** [comment] 2016-07-04 09:35
This issue seems to arise because, after using the fzf Zsh widget, the terminal will not be in application mode anymore. As a result, the terminfo sequences won’t be valid anymore, and will cease to work for people how bound Home and End using these sequences.

I don’t know why exactly the widgets switch away from application mode. Either something in the widget processing will cause `zle-line-finish` to be called (which switches off application mode in my setup), or curses does this (which seems probable).

Since the fzf widgets alter the terminal settings (by calling a curses application), one would probably expect that they restore the original terminal state; so, a fix for this issue would probably go there. I’m not sure which way to go about it best, though. Some options:

- switch back into application mode at the end of each widget unconditionally - this resolves this issue for me, but I’m not sure if there are any drawbacks for folks who don’t set the terminal into application mode in their setup

- detect whether the terminal is in application mode and restore it conditionally

**Comment by eigengrau** [comment] 2016-07-04 10:26
I went for a slightly different solution. Since I couldn’t find a way to query whether we are currently in application mode, so that it can be conditionally restored, we simply run the special hook `zle-line-init` when widgets are finished. In setups using this hook to set the terminal into application mode, this will do the right thing and fix the issue.

**Comment by junegunn** [comment] 2016-07-04 18:03
@eigengrau Great, thanks for the patch! Seems to make sense. Can you post a simple configuration file or script that reproduces the problem we're discussing here? I'd like to locally reproduce the problem on my vanilla zsh and confirm that the patch fixes the issue before merging it.

**Comment by eigengrau** [comment] 2016-07-04 19:18
> I'd like to locally reproduce the problem on my vanilla zsh and confirm that the patch fixes the issue before merging it.

Sure. Actually I made a reproducer config while researching the cause. It’s on my work machine; I’ll shoot you a gist tomorrow.

**Comment by eigengrau** [comment] 2016-07-05 07:01
So here’s the [gist](https://gist.github.com/eigengrau/daa093252cd75ea07deeffd33ca8a260).

**Closed** 2016-07-05 12:50 UTC
