### ISSUE TITLE
history command completion is not correct

### ISSUE THREAD

**Issue by lengxuehx** [junegunn/fzf#1069] opened 2017-09-30 17:26 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I favour the fzf command history feature than the native one. But I encounter a problem when the command is too long. 

When SSH into the remote ubuntu server, which has installed the latest fzf, from my Mac,  I press Ctrl+R and select a command from the command history list and than press Enter, the command shows in screen is a mess. The original command is: 

`source /opt/py_virtualenvs/progress_management/bin/activate; sudo env PATH=$PATH /opt/py_virtualenvs/progress_management/bin/python /opt/progress_management-py/manage.py shell`

but  I get 

`source /opt/py_virtualenvs/progress_management/bin/activate; sudo env PATH=$PATH /opt/py_virtualenvs/progress_management/bin/python /opt/progress_management-py/manage.py shellgement/bin/activate; sudo env PATH=$PATH /opt/py_virtualenvs/progress_management/bin/python /opt`

where `gement/bin/activate; sudo env PATH=$PATH /opt/py_virtualenvs/progress_management/bin/python /opt` is redundant.

<img width="1675" alt="2017-10-01 1 08 20" src="https://user-images.githubusercontent.com/8897643/31047881-235e7bd2-a5d8-11e7-9d42-d61b4398e5e4.png">

<img width="1675" alt="2017-10-01 1 12 27" src="https://user-images.githubusercontent.com/8897643/31047907-b763807a-a5d8-11e7-8195-2d8eb3e2041c.png">

**Comment by junegunn** [comment] 2017-10-07 18:50
Thanks for the report, but it's a duplicate of #681. It's more of a bash issue.

**Closed by junegunn** 2017-10-07 18:50 UTC
