### ISSUE TITLE
Bug: esc/ctrl+[ is more delay than ctrl-c to exit fzf?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3720] opened 2024-04-09 07:46 UTC
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.45.0

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I don't know how to reproduce this but when i press `ctrl+c` to exit fzf, it's faster than `ctrl+[ or esc`, and default `ctrl+[` will be mapped to `esc` which then user can't change this default behavior --> it's bad.

I tried to map like `        --bind=ctrl+t:abort \` --> which produce the same as `ctrl-c` --> fast exit fzf.

so default `ctrl+[ or esc` is not `:abort` action in fzf

so we should allow user to re-map `ctrl+[` and `esc` to `:abort` in fzf or just default them to.

**Comment by junegunn** [comment] 2024-04-09 16:11
Duplicate of https://github.com/junegunn/fzf/issues/2052. You can try setting `ESCDELAY` to a small value, even to 0. It's probably fine on modern terminal emulators.

**Closed by junegunn** 2024-04-09 16:11 UTC

**Comment by junegunn** [comment] 2024-04-09 16:13
> default `ctrl+[` will be mapped to `esc` which then user can't change this default behavior

They are identical on terminals.
