### ISSUE TITLE
Duplicate spaces on bash tab completion

### ISSUE THREAD

**Issue by wzyboy** [junegunn/fzf#375] opened 2015-10-11 13:31 UTC
Hi, thanks for your great work. I have found a little bug in fzf's bash completion scripts.

When using bash completion for `git` subcommands like `git commit`, `git reset` et cetra, fzf will somehow add an extra space to the end of the line.

For example, in a bash session without `source`ing `completion.bash`, when I type `git com` followed by Tab, I get `git commit` with one single space in the end of the line.

However, after `source`ing `completion.bash`, when I type `git com` followed by Tab, I get `git commit` with two spaces in the end of the line.

This, in most cases, will not pose a problem. It will break some completions in some cases though. When I type `git commit --fix` followed by Tab, instead of getting `git commit --fixup=` without any trailing space, I get `git commit --fixup=` with a trailing space. Thus I cannot use further completion like `--fixup=HEAD` without deleting the trailing space first.

**Comment by wzyboy** [comment] 2015-10-11 14:12
![out-o3-c8](https://cloud.githubusercontent.com/assets/459384/10417202/1f6239ce-7065-11e5-820d-239d40c21926.gif)

I managed to make an ugly gif screencast for the bug.

**Comment by junegunn** [comment] 2015-10-11 14:40
Thanks for reporting. This is actually a duplicate of #288. Unfortunately I haven't been able to find a simple solution to the problem.

**Comment by wzyboy** [comment] 2015-10-11 14:43
I searched the issue tracker before reporting this, but did not find that one :-(

Sorry for duplicate reporting, I will subscribe to that issue instead :-)

**Comment by junegunn** [comment] 2015-10-11 14:52
No problem, I changed the title of the issue so that it's easier for others to find.

**Comment by wzyboy** [comment] 2018-02-02 16:04
My fzf (0.17.3) was installed from Arch Linux repo. I have these fzf-related files in bashrc:

```
source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash
```
The bug is introduced in `completion.bash`. After commenting it out, the bug disappears. The `key-bindings.bash` file is fine.

On another Arch installation of mine, fzf 0.17.1 works without bug. So the bug must be introduced in 0.17.2 or 0.17.3.

**Comment by junegunn** [comment] 2018-02-05 02:04
We can continue the discussion on #1203.

**Closed by junegunn** 2018-02-05 02:04 UTC
Labels: duplicate
