### ISSUE TITLE
Error running '/Users/user_name/.fzf/bin/fzf'  ^@ - When using fzf inside Vim

### ISSUE THREAD

**Issue by victorfeijo** [junegunn/fzf#3318] opened 2023-06-02 16:03 UTC
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

It seems like the fzf command is having a weird error when I do `Files` -> `Enter`. The command fails as we can see on the following image:

<img width="1470" alt="Screenshot 2023-06-02 at 11 55 25 AM" src="https://github.com/junegunn/fzf/assets/8865899/33c6fff0-604c-4ff4-826d-05470cd88120">

It's also interesting enough that the `:Files` is working just fine, as we can see below:

<img width="1470" alt="image" src="https://github.com/junegunn/fzf/assets/8865899/604895f7-580a-43a1-9a56-07fda2584f89">

To add more context, if you we do on the command line: `vim $(fzf)` and then select one of the files, it works! However, if inside vim I try to run `:Files` again it fails on the same error.

The config files used to reproduce this issue can be found on here:

- Zsh config: https://github.com/victorfeijo/dotfiles/blob/master/zsh/.zshrc
- Vim config: https://github.com/victorfeijo/dotfiles/blob/master/vimctor/.vimrc

I've tried with Vim, NVim and both have the same issue. Hopefully someone could give me a light here. Thanks!

**Comment by mparent61** [comment] 2023-06-02 20:43
Ran into this same issue today. Confirmed this problem goes away when I pin my Vim plugin to tag 0.41.0
```
Plug 'junegunn/fzf', { 'tag': '0.41.0' }
```

**Comment by junegunn** [comment] 2023-06-02 23:31
Possibly caused by https://github.com/junegunn/fzf/commit/265040a78c50570b0b6e469bfe8fb282de44b115.

* Do you have FZF_DEFAULT_OPTS set?
* Can you test if the problem goes away if you revert the commit?

**Comment by junegunn** [comment] 2023-06-02 23:33
Okay, I can see that you have https://github.com/victorfeijo/dotfiles/blob/0e8a0850c3fe62683c61359d23e496130aafca36/zsh/.zshrc#LL169C1-L172C2.

Let me see what I can do.

**Comment by junegunn** [comment] 2023-06-03 00:04
Should be fixed now, but please let me know if you still have problems.

**Closed** 2023-06-03 00:04 UTC
Labels: bug

**Comment by mparent61** [comment] 2023-06-05 10:51
This works for me, thanks for fixing!

**Comment by victorfeijo** [comment] 2023-06-12 18:53
epic @junegunn , thanks for the fix 🙏🏽
