### ISSUE TITLE
fzf-tmux freezes tmux when run with keybinding

### ISSUE THREAD

**Issue by Eugene-msc** [junegunn/fzf#2058] opened 2020-05-24 17:36 UTC
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Manjaro 20.01
tmux 3.1b
fzf 0.21.1
    
## Problem / Steps to reproduce
I have a tmux command in my .tmux.conf for switching windows it uses fzf-tmux in it. 
It worked all right on ubuntu 19.10 . But now I switched to manjaro and it fails. 
Now it opens the split with the results and then the whole tmux does not accept any keyboard inputs. I cannot close the split or switch panes or type anything.  If I open another terminal and attach to the session it works fine on this another window.
I think it is because of tmux version which changed from 2.9a to 3.1b

The problem is definitely somewhere in fzf-tmux. I reduced the command down to this
```
bind C-f run-shell "echo 'abc' | fzf-tmux"
```
and the result is still the same

I tried opening it in different terminal emulator, switching tmux prefix, switching the C-f keybinding: the result is still the same.

If I just copy the command and run it in terminal it works fine

I tried debugging the fzf-tmux code but failed :(

**Comment by junegunn** [comment] 2020-05-25 09:59
Duplicate of #1841.

See https://github.com/junegunn/fzf/issues/1841#issuecomment-580975759

**Closed by junegunn** 2020-05-25 09:59 UTC
