### ISSUE TITLE
use ccat in preview mode can not get highlighted result

### ISSUE THREAD

**Issue by meritozh** [junegunn/fzf#1158] opened 2017-11-23 15:59 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I use Terminal.app, and there is a tool named [ccat](https://github.com/jingweno/ccat) which can also provide highlight feature. But after test, `fzf --preview 'ccat {}'` won't work as I expect.

So, is there any method that I can get highlighted text content in fzf preview mode?

**Comment by junegunn** [comment] 2017-11-24 04:34
Duplicate of #649.

**Closed by junegunn** 2017-11-24 04:34 UTC
