### ISSUE TITLE
`printenv bash: warning: programmable_completion: printenv: possible retry loop` when attempting to tab-complete

### ISSUE THREAD

**Issue by carschandler** [junegunn/fzf#3712] opened 2024-04-06 03:12 UTC
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.47.0 (0.47.0)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Type `printenv P` and press `TAB`. Usually bash will trigger autocompletion for all environment variables starting with P, but fzf is causing it to throw:
```
bash: warning: programmable_completion: printenv: possible retry loop
```

I'm using NixOS and home-manager to manage my fzf install, and when I set `enableBashIntegration` to `false`, [which prevents the bash completion files from being linked](https://github.com/nix-community/home-manager/blob/782eed8bb64b27acaeb7c17be4a095c85e65717f/modules/programs/fzf.nix#L176-L181), the error goes away.

**Comment by junegunn** [comment] 2024-04-06 07:01
Please test if the problem is reproducible with the latest version, 0.49.0.

**Comment by carschandler** [comment] 2024-04-08 13:35
It will take some time until I can test on 0.49.0, but I also discovered that the issue occurs after `export`, i.e. `export PATH=$PA<tab>`

**Comment by junegunn** [comment] 2024-04-08 15:32
> It will take some time until I can test on 0.49.0

You can just download the binary from https://github.com/junegunn/fzf/releases/tag/0.49.0 and run `eval "$(./downloaded-fzf --bash)"`

**Comment by junegunn** [comment] 2024-04-09 03:22
Likely a duplicate of #3674, and I can't reproduce it with the latest version of 0.49.0. Please reopen if you still have the problem after upgrading fzf.

**Closed by junegunn** 2024-04-09 03:22 UTC
