### ISSUE TITLE
Bottom preview window causes input box to re-render on new line

### ISSUE THREAD

**Issue by PatrickF1** [junegunn/fzf#2512] opened 2021-06-01 16:25 UTC
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish
    
## Problem / Steps to reproduce
1. Prepare some input for fzf that is NUL separated and of differing line lengths. For example, your shell history (assuming you've used previously typed in commands that are multi-line) will do.
2. Send that input into `fzf --read0 --preview="echo {}" --preview-window="bottom:3:wrap"`
3. Start typing the prefix a command that is longer than 3 lines so that the current selected line goes from a command that is only 1 line long to a command that is 4 or more lines long.
4. Notice fzf's window starts rendering incorrectly like this image below:

![Screen Shot 2021-06-01 at 9 17 33 AM](https://user-images.githubusercontent.com/1967248/120358353-3fccee80-c2bb-11eb-936d-b00fb558b98f.png)

**Comment by tuxiqae** [comment] 2021-06-01 20:24
Also happens to me on Arch Linux, using `Alacritty` as terminal emulator

**Comment by junegunn** [comment] 2021-06-02 02:35
Looks like a duplicate of #2508. See if upgrading to 0.27.2 helps.

**Comment by tuxiqae** [comment] 2021-06-02 08:02
> Looks like a duplicate of #2508. See if upgrading to 0.27.2 helps.

Seems like it works on version `027.2` on macOS, I'll check it out on my Arch machine when this version will get released on AUR.

**Closed** 2021-06-02 16:09 UTC
