### ISSUE TITLE
Neovim compatibility

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#137] opened 2015-03-07 15:50 UTC
https://github.com/neovim/neovim/issues/1477

:confused: 

Vim plugin of fzf relies on `:!` for running fzf when not on tmux, and Neovim currently does not (and probably will not) support running interactive programs using `:!`.

**Comment by wellle** [comment] 2015-03-07 16:17
Related: https://github.com/neovim/neovim/pull/2076

**Comment by junegunn** [comment] 2015-03-07 17:15
@wellle Yeah, I'm looking forward to that, but I still wish they don't cripple `:!`.

**Comment by Tranquility** [comment] 2015-03-07 17:27
As far as I know @tarruda just decided not to fix `:!` in the mentioned PR. I am sure he will fix it afterwards.

**Comment by junegunn** [comment] 2015-03-07 17:35
@Tranquility I'm getting the impression that they are adding `:terminal` command to compensate for not fixing `:!`. We'll see. I hope it's fixed. People have always been using `:!` for running external interactive programs in fullscreen mode, ranger, mutt, elinks, to name a few.

**Comment by vheon** [comment] 2015-03-07 21:36
> @Tranquility I'm getting the impression that they are adding :terminal command to compensate for not fixing :!. We'll see. I hope it's fixed. People have always been using :! for running external interactive programs in fullscreen mode, ranger, mutt, elinks, to name a few.

It is not just an impression. It is the way it will works. They have changed the way `:!` works because it would be incompatible with msgpack-rpc UI. So when you will call an external command with`:!` that require to be attached to a tty then the new terminal buffer will be spawned with the command inside.

**Comment by tarruda** [comment] 2015-03-07 22:21
> @Tranquility I'm getting the impression that they are adding :terminal command to compensate for not fixing :!

Actually, the main goal of new terminal facility is to embed and control interactive programs using vimscript. Today I pushed a commit that puts all the logic in the `openterminal` function which returns a job id. That means you can use `jobsend` and `JobActivity` to automate interactive programs in a expect-like fashion(It should be easy to parse gdb output to jump windows to file/lines when a breakpoint is hit, for example).

I may be wrong(because I havent looked into the source code) but I assume plugins like fzf or [selecta](https://github.com/garybernhardt/selecta) only work with vim because they run with inherited stderr connected to a pty, and if so they don't even work in GUI vim. It is more of an accident than a feature, one that can be compared to [this one](https://github.com/neovim/neovim/issues/2088)

> As far as I know @tarruda just decided not to fix :! in the mentioned PR. I am sure he will fix it afterwards.

`:!` can be reimplemented on top of this new terminal facility, but I'm still thinking if its worth the trouble. Consider these facts:

- plugin authors can very easily work around `:!` limitations with `:terminal` or `openterminal()`
- pipes cover most use cases 
- pipes are faster
- pipes are portable to windows(which we don't support yet but hopefully that will change in the following weeks)

Lets elaborate on the first point: While adapting `:!` to open a terminal window would require some hackish changes to Neovim source code(which would only there for the sake of a few plugins), plugin authors can very easily adapt their code for Neovim. For example, fugitive could change `:!git add -p`(as reported by @Tranquility) to `sp | term git add -p` when running under neovim. It would probably be easy to integrate selecta and fzf with neovim using `openterminal`

But the last point is the most important: `:terminal` will be supported on windows via [winpty](https://github.com/rprichard/winpty), but it would be very expensive to use it in every call to `:!` and `system` since it relies on spawing hidden console windows and polling to emulate the pty interface. Imagine doing that just for reading a command stdout.

**Comment by junegunn** [comment] 2015-03-08 00:36
@tarruda fzf redirects ncurses output to stderr, and prints the list of selected items to stdout. It's using `:!` because there's no other way. In case of fzf, `:terminal` is a big plus since it's using some serious hacks to open it in on a new tmux pane (similarly to dispatch.vim by tpope) not to take up the entire screen, or on an external terminal emulator when on gvim. So there's no reason for fzf to want `:!` once `:terminal` is implemented. Rather than plugins, I was more referring to the way people have casually used `:!` for the previous years, using it to open TUI programs (e.g. mutt, elinks) in fullscreen mode with full control over TTY.

**Comment by tarruda** [comment] 2015-03-08 00:55
> @tarruda fzf redirects ncurses output to stderr, and prints the list of selected items to stdout. It's using :! because there's no other way. In case of fzf, :terminal is a big plus since it's using some serious hacks to open it in on a new tmux pane (similarly to dispatch.vim by tpope) not to take up the entire screen, or on an external terminal emulator when on gvim. So there's no reason for fzf to want :! once :terminal is implemented. Rather than plugins, I was more referring to the way people have casually used :! for the previous years, using it to open TUI programs (e.g. mutt, elinks) in fullscreen mode with full control over TTY.

Glad to know `:terminal` will be useful for running fzf with neovim.

Right now its not possible to redirect stdout to a pipe and stream data separately from ncurses output, but that is clearly useful and something I can add later. For now you might be able to handle the problem with `mkfifo`, manual shell redirection and `cat` spawned as a parallel job.

**Comment by junegunn** [comment] 2015-03-09 17:00
I'll wait until `:terminal` is ready.

I updated the vim plugins with the new `up` / `down` / `left` / `right` options to replace `tmux_height` and `tmux_width`. I removed `tmux_` prefix because I'm goint to use native Vim splits instead of tmux panes on Neovim when `:terminal` is ready.

**Comment by jebaum** [comment] 2015-03-10 04:40
If fzf adds support to its vim plugin for opening in nvim `:terminal`, is it also possible that it'll add some keymaps? I.e. in CtrlP, you `C-t` on selected file(s) to open in tabs, `C-s` in splits, `C-v` in vertical splits, etc. Or would it stay the same as it is currently, with having to decide when you call `fzf#run()` how you want the files opened? I can see the argument against adding keymaps to fzf, since it's supposed to just be a filter of stdin, but the behavior of CtrlP in terms of choosing how to open files feels much more natural.

**Comment by junegunn** [comment] 2015-03-10 04:47
@jebaum 
> If fzf adds support to its vim plugin for opening in nvim :terminal, is it also possible that it'll add some keymaps?

Hmm, I don't know. Maybe `tnoremap` will allow us to do that?

**Comment by jebaum** [comment] 2015-03-10 05:06
Oh good point, I could imagine that being possible. I will definitely look forward to playing with that

**Comment by junegunn** [comment] 2015-03-26 03:08
https://github.com/neovim/neovim/pull/2076 is now merged, and fzf works surprisingly well inside term buffer. :tada: The only thing that does not work is shift-click or shift-scroll for selecting multiple items when `--multi` option is given.

**Comment by junegunn** [comment] 2015-03-26 03:43
![nvim-fzf-prototype](https://cloud.githubusercontent.com/assets/700826/6840060/8e5c742c-d3b5-11e4-883f-ab44022fc0eb.gif)

Issues:
- Shift-TAB / shift-click / shift-scroll not working
- Need to avoid `[Program exited, press any key to close]` prompt
- Need to change the name of the buffer
- Need autocmd for program exit

**Comment by tarruda** [comment] 2015-03-26 09:04
@junegunn I suggest waiting for neovim/neovim#2247(which will me merged until tomorrow) before merging this change

**Comment by junegunn** [comment] 2015-03-26 09:12
@tarruda Thanks for the heads up, it's nowhere near complete anyway :)

**Comment by junegunn** [comment] 2015-03-28 18:34
@jebaum In the meanwhile, ctrlp-compatible key bindings (CTRL-T/X/V) for `:FZF` are now implemented using `--expect` option of 0.9.6.

**Comment by jebaum** [comment] 2015-03-29 10:35
I really like that way of doing it, very unobtrusive, although wouldn't your original `tnoremap` idea still work as well?

I think there's still some support needed from neovim so that the stdout of fzf can be used to open a file, unless I'm missing something. Then the next step would be making lists of other type of data inside neovim available to send to fzf (or any other external program), like the list of currently opened buffers, contents of the quickfix/location list, command history, etc. One thing that unite.vim has that's particularly handy sometimes is its `line` source, which can list all the lines in every open buffer (`:Unite line:buffers`) , and selecting a line jumps to it.

anyway, this was just brainstorming about the various ways I'd like to use fzf with neovim :terminal mode, maybe you've already thought of all of them.

**Comment by tarruda** [comment] 2015-03-29 10:52
> I think there's still some support needed from neovim so that the stdout of fzf can be used to open a file, unless I'm missing something. 

I  considered adding a `termopen` option to redirect stdout or stdin to pipes, so another data channel that doesn't affect the terminal window can be used for communication between the program and Neovim. The only reason I didn't do it yet is because I want job control to be as cross platform as possible, and I don't know if this behavior will be portable to windows.

For now here's a couple of options:

- Use `$NVIM_LISTEN_ADDRESS` to open a connection to Neovim and tell it to open the file
- Use a named pipe and job control to receive information about which file should be opened.

I think the second approach is simpler because it wont require modifying `fzf` to connect with Neovim. Here's a possible way to do it: `:term mkfifo fzf-data && fzf > fzf-data`(assuming fzf uses stderr to communicate with the terminal) and open the pipe using `cat` or a similar program: `call jobstart(['cat', 'fzf-data'], ...)`

One thing I will add to Neovim in the next days is a `TermClose` autocmd, so you can use it to automatically close the terminal window once the fzf exits

**Comment by junegunn** [comment] 2015-03-29 12:11
@jebaum 
> I really like that way of doing it, very unobtrusive, although wouldn't your original tnoremap idea still work as well?

Neovim is not my primary editor (yet), and I'm always on tmux, so I currently have no issue running fzf on vim and now I can even have custom key bindings with `--expect` option. We can still use `tnoremap` instead on Neovim, but I don't see the point. There's no reason to implement two different ways to do the same thing. The neovim version of fzf plugin should only differ in the way it launches fzf, the rest of the code does not need to be changed.

> I think there's still some support needed from neovim

Not much. Have you tried the examples on [the wiki page](https://github.com/junegunn/fzf/wiki/Examples-(vim))? I'm using fzf on vim to [open files](https://github.com/junegunn/dotfiles/blob/8318f4c/vimrc#L1322-L1325), [switch buffers](https://github.com/junegunn/dotfiles/blob/8318f4c/vimrc#L1340-L1359), [select color scheme](https://github.com/junegunn/dotfiles/blob/8318f4c/vimrc#L1327-L1338), or [go to a line in any open buffer](https://github.com/junegunn/dotfiles/blob/8318f4c/vimrc#L1382-L1405) (I think this is equivalent to the line source of unite you mentioned) using horizontal/vertical tmux panes. No need to complicate, simple uses of temporary files should suffice in most of the cases. The only thing that I need at the moment is `TermClose` autocmd @tarruda mentioned.

**Comment by tarruda** [comment] 2015-03-29 12:37
@jebaum note that you can add your own custom mappings for fzf with something like this:

```vim
au TermOpen term://*fzf tnoremap <buffer> ...
```

**Comment by junegunn** [comment] 2015-04-10 04:58
@tarruda Hi, are you still planning to add `TermClose`? For this to work, I need a way to either
- synchronously and exclusively run fzf
- or get notified when the process is complete so I can take the next step.

**Comment by tarruda** [comment] 2015-04-10 07:51
@junegunn Yes I will add `TermClose`. I'm just waiting a few days for the community to give more feedback on the terminal emulator before I start fixing bugs and enhancing it.

But there's a temporary workaround you can use to get an exit notification: Just spawn the terminal with [`termopen`](http://neovim.org/doc/user/eval.html#termopen()) which is similar to `jobstart`. Here's a little snippet to get you started:

```vim
let Fzf = {}

function Fzf.on_exit(id, code)
  call feedkeys("\<c-\\><c-n>:bd! ".self.bufid."<cr>", 'n')
endfunction

sp | enew
let fzf = extend(copy(Fzf), {'bufid': bufnr('%')})
call termopen('ls ~; sleep 3', fzf)
startinsert
```

Note that the `feedkeys` hack is required because nvim will crash if you call `bd!` directly while the terminal is focused(it's on my list of fixes :smile:). Also, the `enew` is required because `termopen` will use the current buffer to spawn the terminal(this is done so terminals are restored by scripts created with `:mksession`)

If you'd rather wait for `TermClose` I might add it this weekend.

**Comment by junegunn** [comment] 2015-04-10 07:59
@tarruda Good to know, thanks!

**Comment by tarruda** [comment] 2015-04-10 08:08
@junegunn Actually the crash I mentioned earlier is gone, thanks to @splinterofchaos. The following should also work:

```vim

let Fzf = {}
function Fzf.on_exit(id, code)
  exe 'bd!' self.bufid
  echo "Terminal closed"
endfunction

sp | enew
let fzf = extend(copy(Fzf), {'bufid': bufnr('%')})
call termopen('ls ~; sleep 3', fzf)
startinsert
```

**Comment by junegunn** [comment] 2015-04-10 08:12
@tarruda Ah, okay. Then I'll try to implement using the above approach.

**Comment by junegunn** [comment] 2015-04-10 14:53
![nvim-fzf](https://cloud.githubusercontent.com/assets/700826/7089995/eceb1864-dfda-11e4-91c5-6ff5e5289bbf.gif)

Pushed the update. Please test it if anyone's interested. I tried to make neovim version as close to the original as possible.

A few points to mention:

- Since `fzf#run()` call is asynchnous on Neovim, we can't make it return the list of the selected items as before. Instead I added `sink*` option which is a funcref to the callback function that takes the list.
- Added `window` option just for Neovim. It's the command used to open fzf window.
    - e.g. `vertical aboveleft 20new`
- When none of `up`/`down`/`left`/right`/`window` option is given, fzf will start on `tabnew` to mimic fullscreen behavior on Vim.

Issues:
- When I open a file with fzf, sometimes I'm left with the file with its content modified to `[Program exited, press any key to close]`. Not really sure why.
- `Shift-tab` for selecting multiple items does not work (/cc @tarruda)
    - `nnoremap <s-tab> :echom reltime()[1]<cr>` works on Neovim. But it doesn't work on Neovim opened inside `:term`

**Comment by tarruda** [comment] 2015-04-10 15:29
I already replaced ctrlp by fzf and couldn't be happier

> Since fzf#run() call is asynchnous on Neovim, we can't make it return the list of the selected items as before. Instead I added sink* option which is a funcref to the callback function that takes the list

Currently `jobwait` is broken, but maybe it can be used to implement a synchronous version later.

> When I open a file with fzf, sometimes I'm left with the file with its content modified to [Program exited, press any key to close]. Not really sure why.

Are you saying that the terminal buffer is shown instead of the file? Any hints on how to reproduce?

> Shift-tab for selecting multiple items does not work (/cc @tarruda)
nnoremap <s-tab> :echom reltime()[1]<cr> works on Neovim. But it doesn't work on Neovim opened inside :term

It seems shift-tab is not forwarded by `:term` correctly. I will investigate(added a note to neovim/neovim#2277)

**Comment by junegunn** [comment] 2015-04-10 15:52
> Are you saying that the terminal buffer is shown instead of the file? Any hints on how to reproduce?

Yes, just `[Program exited, press any key to close]` message and nothing else. I checked the undo list of the buffer and it was clear. I ran into it only a few times, and I haven't found a reliable way to reproduce the case. I'll let you know if I figure it out.

**Comment by junegunn** [comment] 2015-04-10 16:12
![exit-buffer](https://cloud.githubusercontent.com/assets/700826/7091645/36b19eae-dfe6-11e4-9349-8d3e193ffb10.png)

@tarruda This is how it looks like. If I press any key in this state, the tab is immediately closed. But if I press `<C-\><C-n>` to escape the terminal, I'm left with the buffer on the tab and the it's `&modified` but with no undo list. I still am not sure how to reliably reproduce it, but it seems to happen only when I open the file in a new tab with `<CTRL-T>` key binding of `:FZF` command.

I use this mapping:

```vim
nnoremap <silent> <Leader><Leader> :FZF -m<CR>
```

1. `<space><space>` to start fzf
2. type in some pattern
3. press CTRL-T

**Comment by splinterofchaos** [comment] 2015-04-10 16:13
I've had this happen too. Start nvim in a sufficiently large file like (from nvim's source dir) `src/nvim/eval.c`. Then run `:FZF` to open a sufficiently small file, like `BACKERS.md`. The screen will be blank. (May have to try more than once.) Scrolling with the mouse to the top line will reveal that the second like has `[Program exited, press any key to close]` and the file should be truncated, but pressing enter instead will flash the file on screen then return to the previous file.

I think this happens because the terminal program closes and somehow the current buffer begins filling with the new file, but the current buffer still thinks it has a terminal. It soon realizes the program has exited and acts as if the new file is a terminal.

**Comment by adambiggs** [comment] 2015-04-10 16:47
@junegunn @tarruda awesome work guys! FZF in NeoVim is blazing fast!

**Comment by Tranquility** [comment] 2015-04-10 18:57
Really nice! :+1: 

Can you think of any way to adjust the buffer size with the number of hits?

**Comment by junegunn** [comment] 2015-04-11 01:16
@adambiggs Thanks!

@Tranquility I also thought about that. We probably could use some autocmd to monitor the number in the buffer and resize it accordingly.

**Comment by noahfrederick** [comment] 2015-04-11 01:50
This has been working great.

With `:set cmdheight=2` the following text is shown in the command-line area when fzf is open:

    "[FZF]"  4 lines --25%--
    -- TERMINAL --

It might be nice to clear that message on the first line, since it represents visual clutter and provides no useful information in this context.

**Comment by junegunn** [comment] 2015-04-11 02:19
@noahfrederick Fixed it, thanks for the suggestion!

**Comment by mtglsk** [comment] 2015-04-11 12:51
:set laststatus=0
    :vnew
    :new
    :FZF<CR>

Screen gets garbled and cmdheight increases +1.

**Comment by junegunn** [comment] 2015-04-11 14:56
@mtglsk It's reproducible even without fzf plugin.

```vim
:set laststatus=0 | vnew | new | botright 20new | q
```

**Comment by mtglsk** [comment] 2015-04-11 15:12
Ok, i opened a bug on neovim.

**Comment by junegunn** [comment] 2015-04-11 15:17
@mtglsk Ugh, it's also reproducible on Vim.

**Closed** 2015-04-14 17:12 UTC
Labels: enhancement

**Comment by tamagokun** [comment] 2015-04-14 18:08
Been watching this thread, and think I am definitely missing something.

I've reinstalled both fzf and neovim from HEAD and am getting the following:

![screen shot 2015-04-14 at 2 07 34 pm](https://cloud.githubusercontent.com/assets/487333/7143850/b2f8b0f8-e2af-11e4-9b91-bf9f9212302a.png)

**Comment by junegunn** [comment] 2015-04-15 01:52
@tamagokun Alright, make sure to run the install script after update so that it downloads the latest Go binary for your platform. Or you can just set up a post-update hook and forget about it.

```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
```

**Comment by tarruda** [comment] 2015-04-15 10:43
Just wanted to let you guys know that I'm aware that there are still problems with Neovim/fzf integration, but it's Neovim bugs which I will fix as soon as I have time.

**Comment by tamagokun** [comment] 2015-04-15 11:28
@junegunn for what it's worth, I was reinstalling fzf using Homebrew (`brew reinstall --HEAD fzf`) and forgot that I also needed to update the vim plugin.

**Comment by junegunn** [comment] 2015-04-15 11:47
@tarruda Thanks!

@tamagokun In that case, you don't need to separately install/update vim plugin, as it's already included in Homebrew package and updated when you `reinstall`. You can remove `Plug` line from your .vimrc, add `set rtp+=/usr/local/Cellar/fzf/HEAD` and you're set.

**Comment by tamagokun** [comment] 2015-04-15 11:48
@junegunn aha! Of course. Thanks!

**Comment by justinmk** [comment] 2016-02-26 00:04
> are you still planning to add TermClose? For this to work, I need a way to either

@junegunn Not sure if you still need it, but `TermClose` was added some time ago, and I noticed fzf doesn't seem to be using it.

**Comment by junegunn** [comment] 2016-02-26 00:15
@justinmk No, I was just unaware of `on_exit` callback when I asked for it.
