### ISSUE TITLE
$FZF_DEFAULT_COMMAND not working but "ag -l -g "" | fzf" works

### ISSUE THREAD

**Issue by vysakh0** [junegunn/fzf#210] opened 2015-04-22 06:05 UTC
I have few files ignored in `.agignore`. These files are correctly ignored when I run `ag -l -g "" | fz`.  

But this does not work when I run `Ctrl-T`. I checked 
```bash
 echo $FZF_DEFAULT_COMMAND 
#=> ag -l -g "" 
```

ag --v: ag version 0.15pre
fzf --version: 0.9.10

(In this gif, I'm searching for tmp directory which does not appear as expected first time but not when run with Ctrl-T)

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/1475197/7268451/409ceaa4-e8e7-11e4-8c0c-005a82db68e8.gif)

Please, help me where I'm wrong.

**Comment by junegunn** [comment] 2015-04-22 07:16
This is essentially the same question as #40 and I haven't decided how it should be handled. `CTRL-T` does not see `FZF_DEFAULT_COMMAND` and as you can see in my comments in the issue, I'm not sure if it should. (If you use `ag` for `CTRL-T`, it will not list directories) So currently there's no way to customize the behaviors of the key bindings and you'll have to write your own version based on the default implementation.

Closing as duplicate of #40. Thanks.

**Closed by junegunn** 2015-04-22 07:16 UTC
