### ISSUE TITLE
fzf and neovim issue

### ISSUE THREAD

**Issue by aliev** [junegunn/fzf#221] opened 2015-05-02 06:40 UTC
when I try to open a second file the buffer is closed

video: https://dl.dropboxusercontent.com/u/5837324/fzf-neovim-issue.mov

**Comment by alerque** [comment] 2015-05-02 09:50
Similar problem here, but it's not _every_ second file. It's only happens about 1/2 the time, and I can't figure out what the conditions are. Once it fails it fails for the same file all the time. Quite often if I try opening in a tab instead of a split it will open. When that fails if I start a new buffer with `:tabnew` before running FZF it and it will open in that fine. Once it does open I can also go back to to the previous tab and open it fine in that. Also I don't see the error message you're seeing and can't figure out how to get more verbose information about what's going on. I think some message is being thrown or some input being waited for, but I can't see it.

**Comment by alerque** [comment] 2015-05-02 10:01
This looks like a duplicate of #206.

**Comment by aliev** [comment] 2015-05-02 13:54
@alerque 
> I think some message is being thrown or some input being waited for, but I can't see it.

sorry. I see the following kind error

[Program exited, press any key to close]

**Comment by junegunn** [comment] 2015-05-02 15:07
Thanks for the report. But now we know that the terminal feature of Neovim is unstable at the moment and fails in some different ways, so there's no need to create more issues. Closing as duplicate.

**Closed by junegunn** 2015-05-02 15:07 UTC
