### ISSUE TITLE
Select first item whenever query changes

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf#925] opened 2017-05-17 18:18 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Sorry to create many issues in your repository.
Is it possible to make fzf select first item whenever query changes?

**Comment by junegunn** [comment] 2017-05-21 16:39
What would be the motivation for this? Can you give me an example?

**Comment by sassanh** [comment] 2017-05-21 17:04
You run fzf, you query something (or nothing) and you go 50 items above investigating the results and you conclude you need some other query, when you change the query most of the time you want to see the high score results first but in this case you should:
1. Be aware that the results in front of you are low score results (fzf has no scroll bar or any other indicator that shows where are you in the list)
2. Take action to go to the beginning of the list.

If you add this option for fzf I'll put it in my default options for fzf cause I always prefer to go to the beginning of the list when I change the query.

**Comment by junegunn** [comment] 2017-05-22 07:27
Okay.

A non-disruptive way to add the feature would be to add a bindable action, so that one can bind it to a key that is commonly used to reset the query prompt, such as ctrl-u (`--bind ctrl-u:unix-line-discard+top`). But if one wants to move the cursor to the first element whenever the query string is changed, not only when it's cleared, then we would need a new, non-keyboard "event" in addition to the action (`--bind change:top`).

**Comment by sassanh** [comment] 2017-05-22 07:34
Suppose that you wanna change the query from "boochapnotcomm" (for book chapter notes comments) to "boochapnotlik" (last changed to likes). Hitting `<c-u>` doesn't feel good here. Adding the `change` action would be helpful I think.
Also based on your suggestion I thought maybe we can have something like `loaded:up(12)` this way we can have "navigate on initialization" feature requested in another issue. What do you think?

**Comment by junegunn** [comment] 2017-05-22 07:37
I don't like having an option for setting the initial position because of asynchronous nature of fzf. It complicates the implementation in corner cases.

**Comment by sassanh** [comment] 2017-05-22 07:54
But the action I suggested is not `initialized` it's `loaded`. Do you think it's still not achievable with a clean implementation?

**Comment by junegunn** [comment] 2017-05-22 08:04
fzf consumes its input asynchronously, and it does not block the user interface while the input stream is still open.

```sh
for n in $(seq 100); do sleep 1; echo $n; done | fzf
```

I'm not sure if I understood your point correctly, but if by "loaded" you mean when the stream is complete, the user may have moved the cursor to some location at that point. Suddenly moving the cursor automatically because the stream is complete can be confusing to the user and we can't determine if it's desirable or not, and that calls for a yet another option, which I'd like to avoid.

**Comment by sassanh** [comment] 2017-05-22 08:37
@junegunn I understand there are cases when input stream may finish few seconds or even minutes after fzf opens. But there are also many cases when the input stream finishes in less than .2s after fzf opens. If we give the user the `loaded` event, he can decide when to use it and when to not.

I like your idea of keeping the core small when features can be implemented with plugins/user customization/etc but I don't like the idea of avoiding a feature to keep the core small even when it's not feasible to achieve it with plugins/customization/etc or it's really hard and needs hacky implementations.

What do you think?

**Comment by junegunn** [comment] 2017-05-22 09:07
Well, as the maintainer of the project, I have to prevent feature creep and I'm not convinced that the feature you requested is crucial to fzf at the moment, that's it. I may change my mind, but that's how I feel about it now. Some users have tried to use fzf as a building block for their sophisticated TUI programs and requested many features for very specific use cases that most users of fzf, including myself, who still see it just as an interactive grep, would never need. I have mixed feelings about their approaches. Just because you can do cool stuff with fzf doesn't mean that it's the best tool for the purpose.

You might want to give some concrete examples of what you're trying to do with the option. maybe there are other users with similar requirements.

**Comment by sassanh** [comment] 2017-05-22 09:22
I understand your concerns, but I think request to complete api shouldn't be confused with request for new feature. I'm not asking to implement some code so that fzf can get aware if the input stream is complete, I'm just asking if fzf already knows when input stream is complete, reflect it on api by firing an event. If some new code is required for fzf so that it can understand input stream is complete, then it's a new feature, but if it already knows it and just doesn't reflect it on api, then it's just completing the api.

**Comment by junegunn** [comment] 2017-05-22 19:48
That's a bit of a stretch. `--bind` was designed to handle events triggered by user input, keyboard and mouse. The `change` event I added to devel branch is still a derivative event of keyboard events, and that's why it was possible to add support for it without too much new code. Just because `--bind` now supports it doesn't mean that it also has to support other numerous internal events of different types with different code paths.

You still haven't explained why you need the option and what you are trying to implement with it. Maybe I could suggest alternative ways to achieve your goal, or maybe I'll change my mind after hearing your use case.

Anyway, since the original issue is resolved, I'll close this. The new option will be available in the next release.

**Closed by junegunn** 2017-05-22 19:48 UTC
Labels: feature

**Comment by sassanh** [comment] 2017-05-22 20:09
Thanks, I'm already using the devel branch and it's working great.
My usecase is not easy to describe. I rather deal with --header-lines. I just thought it's easy to add this event but if it needs extra work I'm sure it doesn't worth - at least in my case.

**Comment by uri** [comment] 2017-06-02 14:32
`unix-line-discard+top` is exactly what I'm looking for. I can a stab at PR.

**Comment by junegunn** [comment] 2017-06-02 15:29
It's already implemented on devel branch. A new release is coming in a few days.

**Comment by uri** [comment] 2017-06-07 15:35
Adding a comment to indicate that `unix-word-rubout+top` is now in master. Thank you for all your hard work!
