### ISSUE TITLE
[neovim] :FZF sometimes fails to open certain files

### ISSUE THREAD

**Issue by adambiggs** [junegunn/fzf#206] opened 2015-04-20 17:50 UTC
Sometimes when I `:FZF`, select a file, and then press `<Enter>`, NeoVim becomes unresponsive.

When this happens, pressing `<Enter>` a couple more times brings up the following:

```
W10: Warning: Changing a readonly file
E315: ml_get: invalid lnum: 570
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 568
Press ENTER or type command to continue
E315: ml_get: invalid lnum: 403
Press ENTER or type command to continue
...
```

Interestingly, opening the same file in a split (via `<C-v>`) seems to work, although nothing happens until I press `<Enter>` one extra time... i.e. `<C-v>` *nothing happens* `<Enter>` *buffer opens as expected*.

Quitting & relaunching NeoVim seems to make the problem go away for a while, so it's difficult to reproduce.

**Comment by junegunn** [comment] 2015-04-21 00:09
Thanks. This also looks like a neovim issue. /cc @tarruda

**Comment by tarruda** [comment] 2015-04-21 02:03
@junegunn can you assign this and any other neovim-related issues to me?

**Comment by junegunn** [comment] 2015-04-21 02:44
@tarruda Okay, I'll (temporarily?) add you as a collaborator. Just a second.

**Comment by tarruda** [comment] 2015-04-21 03:44
> @tarruda Okay, I'll (temporarily) add you as a collaborator. Just a second.

Thank you, I find easier to keep track of issues if they are assigned to me. I will address them ASAP.

**Comment by adambiggs** [comment] 2015-04-21 06:10
Thanks once again @tarruda!

**Comment by shkm** [comment] 2015-04-22 16:37
Something similar seems to be happening to me, but I don't see any errors in `:messages`, making it a little hard to debug.

**Comment by schmooser** [comment] 2015-04-23 09:17
I'm observing this as well. Usually on second attempt it works. I failed to reproduce this behaviour intentionally so I didn't raise an issue.

**Comment by edi9999** [comment] 2015-05-01 08:39
Same issue for me 

E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58
E315: ml_get: invalid lnum: 58

**Comment by cHoco** [comment] 2015-05-01 20:50
I have the same issue, but I don't get any errors only  ```[Program exited, press any key to close]``` 
after selecting the file I want to edit. Also it happens for every file for me, making fzf unusable for me in neovim :( Strangely if I select the file with CTRL-V it works as expected

**Comment by kennethlee** [comment] 2015-05-02 05:06
@tarruda I'm having issues similar to @cHoco as well.

If I search for and select a file while I already have another file open in the current buffer, I get `[Program exited, press any key to close]`. However, if the current buffer is empty, :FZF works as expected.

**Comment by alerque** [comment] 2015-05-02 10:04
Having the some issue here, but unlike @kennethlee my case isn't quite as cut and dry. It works in an empty buffer, but _sometimes_ works even if the buffer has a file open and as @adambiggs noted _sometimes_ will be fixed by requesting a split or tab, but not always. It is only consistent as long as I keep trying to open the same file, but as soon as I open it in a clean buffer and close it, I can open it in the dirty buffer that originally failed.

**Comment by justinforce** [comment] 2015-05-04 17:50
I'm experiencing this, too. I find that opening in a split works, but hitting Enter will actually sometimes result in inserting `[Program exited, press any key to close]` in the file around the 3rd line, then **truncating the file!** >_< Just one more reason to love git. :)

**Comment by Tarmean** [comment] 2015-05-23 13:26
For me it is prety easy to see when the issue hapoens because it stays in terminal mode after switching to the new buffer. Leaving terminal mode with esc-esc breaks the new buffer with the same reason as justinforce. Reloading with e! % or going back with g- works.

Any other button closes the new buffer for me. Happens with empty or loaded buffers seamingly at random.

**Comment by babygau** [comment] 2015-05-28 14:21
Guys,

This seems to be fixed properly. Now I can open every file with "Enter" key. Could anyone confirm this so that we could close this issue? Because I updated both `neovim` and `fzf` so I don't know which one fix the bug. 

Here is my `fzf` config that allows me to use <C-P> to activate `fzf` window and open new buffer window with `Enter` key
```VimL
"" FZF CONFIG
"" ----------
nnoremap <silent> <c-p> :<c-u>call fzf#run({
    \ 'options': '-m',
    \ 'down': 20,
    \ 'sink': 'e'
    \ })<cr>
```

**Comment by shkm** [comment] 2015-05-28 15:41
Happy to hear it! I went back to vim for the time-being, but FZF breaks zoom in it (as it opens a Tmux pane instead of a Neovim terminal). Will try tomorrow!

**Comment by Tarmean** [comment] 2015-05-28 17:50
Nope, definitely still happening when doing two searches in succession.

**Comment by cartolari** [comment] 2015-05-28 17:58
There are some open issues about Neovim terminal emulator integration with FZF. Today I have updated both Neovim and FZF and none of them appear to be happening anymore. I use neovim from the custom Ubuntu ppa.

**Comment by justinforce** [comment] 2015-05-28 19:00
Another data point: I updated Neovim and FZF to HEAD and I'm no longer experiencing this. 

```
phong:~% fzf --version
0.9.12
phong:~% nvim --version
NVIM 0.0.0-alpha+201505271256 (compiled May 28 2015 11:52:08)
Commit: ee312ca9a4d35132059db80b13153ce71faa4ae6
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150528-16178-15csfih/build/config -I/tmp/neovim20150528-16178-15csfih/src -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/tmp/neovim20150528-16178-15csfih/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150528-16178-15csfih/build/src/nvim/auto -I/tmp/neovim20150528-16178-15csfih/build/include
Compiled by force@phong.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim
```

**Comment by justinmk** [comment] 2015-05-28 20:36
@Tarmean what were the precise steps you took to update neovim?

**Comment by edi9999** [comment] 2015-05-29 07:13
Same as @Tarmean for me, even with a pretty void `.nvimrc` : 

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
"
let mapleader = ","

if has('vim_starting')
  " Required:
  set runtimepath+=~/.nvim/bundle/neobundle.vim/
endif

set rtp+=~/.fzf

nnoremap <silent> <C-f> :<c-u>call fzf#run({
    \ 'options': '-m',
    \ 'down': 20,
    \ 'sink': 'e'
    \ })<cr>

" nnoremap <silent> <C-f> :FZF<CR>
command! FZFTag if !empty(tagfiles()) | call fzf#run({
\   'source': "sed '/^\\!/d;s/\t.*//' " . join(tagfiles()) . ' | uniq',
\   'sink':   'tag',
\   'options':  '+m',
\   'left':     60,
\ }) | else | echo 'No tags' | endif

nnoremap <silent> <Leader>t :FZFTag<cr>
```

To update neovim, I use the `add-apt-repository ppa:neovim-ppa/unstable -y`

and an `apt-get update`

Here is the result of 

```
nvim -v
NVIM 0.0.0-alpha (compiled May 27 2015 19:43:48)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/build/config -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/src -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-Fsnk6w/neovim-0.0.0+git201505271334+1658+9+10~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-25

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

I also have the latest versions of fzf, which I pulled and then run the `./install` script.

**Comment by babygau** [comment] 2015-05-29 12:56
Well, I'm not sure about Linux bcoz OSX running OK with me

**Comment by shkm** [comment] 2015-05-29 13:34
Latest versions of Neovim and FZF, still having issues.

**Comment by Tarmean** [comment] 2015-05-30 18:20
I used apt-get to install it from neovim-ppa/unstable and removed/reinstalled it once since for another reason. So reasonably certain it doesn't have to do with the install itself. This is on linux mint btw.

**Comment by babygau** [comment] 2015-05-31 15:18
So it's weird then,
@Tarmean, could you try to upgrade python neovim too? by running `pip install --upgrade neovim`. 
I don't know what's wrong but mine is working OK.

**Comment by justinmk** [comment] 2015-05-31 16:35
Latest master could possibly help with this issue.

**Comment by jgkamat** [comment] 2015-06-28 17:07
Definitely still happening for me, I tried updating python as well. I'm running the latest fzf and the latest neovim in the ubuntu ppa.

**Comment by alerque** [comment] 2015-06-29 06:48
@jgkamat Same here. Error situation has changed a little but it's still bombing out.

**Comment by tarruda** [comment] 2015-06-30 11:28
I have tried to reproduce this now with no success. Opened files in empty or filled buffer, in splits, and it always worked. Is anyone experiencing this on master? (more precisely @fa13cc61c)

**Comment by alerque** [comment] 2015-06-30 14:33
@tarruda I've been on fa13cc6 most of the day and have seen this at least 20. Per usual it doesn't happen every time but it's over 50 of the time. I've been doing mostly `:edit <path>` from nvim this afternoon just to avoid the pain of having it bomb.

**Comment by cHoco** [comment] 2015-06-30 14:44
Still happens from time to time to me. I can't talk for the others, but it usually happens with really small files.
EDIT: actually I can reproduce it right now almost 100% but doing this

1. Create empty file ```touch test``` 
2. Open neovim ```nvim```
3. Launch fzf ```:FZF```
4. Select the test file and press enter key ```test<CR>```
5. The file is opened but press any key and the file is closed

**Comment by jgkamat** [comment] 2015-06-30 14:58
For me those steps don't work :cry: 
When I try disabling all my plugins except for fzf, everything works as expected, but I cant seem to pin the problem down to a single plugin. It seems more like its related to the slowdown accompanying some plugins? I'm not sure about this, but I have a hunch that it's related to performance somehow. Does anyone have any tips for debugging which plugins could be causing this?

**Comment by cHoco** [comment] 2015-06-30 15:53
Yeah, I can confirm that without plugins it works. But i tried to identify the one causing the problem and wasn't able to. It seems to depend on the number of plugins, not the plugins per se. And since it doesn't happen all the time with any file I suppose it must be some kind of race condition.

**Comment by tarruda** [comment] 2015-06-30 16:13
@cHoco / @jgkamat / @alerque 

Do you use any python plugins? If so, does the problem still happens when you disable python?(add `let g:loaded_python_provider = 1` to the top of your vimrc)

**Comment by cHoco** [comment] 2015-06-30 16:26
Yes I use some python plugins (YCM being the most "expensive" one). Disabling python seems to "fix" it for me. I've been trying for a solid 5 minutes to open various files and I wasn't able to trigger the bug.

**Comment by alerque** [comment] 2015-06-30 16:27
@tarruda I do use python plugins. I just disabled that as you suggested and in a quick test opening a couple dozen files in hasn't failed once. `nvim`+`fzf` haven't been this nice to me in months.

**Comment by jgkamat** [comment] 2015-06-30 16:51
I don't think I have any python plugins (I got no errors when adding that line), and adding that line seemed to improve things slightly, but i'm not sure about that. :disappointed:

**Comment by tarruda** [comment] 2015-06-30 17:01
> I don't think I have any python plugins (I got no errors when adding that line), and adding that line seemed to improve things slightly, but i'm not sure about that. :disappointed:

did you manage to reproduce the bug after adding that line?

FWIW, I don't think this is related to python provider, but a long-existing nvim issue which I have been working to fix for the past couple of months:  neovim/neovim#2371. The fact that disabling python makes it harder to reproduce is just a consequence of how nvim processes asynchronous messages.

**Comment by jgkamat** [comment] 2015-06-30 17:05
Yes I did, sorry for not making that clear before. Maybe I'm seeing a different issue from @alerque and @cHoco?

**Comment by tarruda** [comment] 2015-06-30 17:07
Your first comment:

>  I'm not getting the error messages anymore, the opened window/split just crashes. (Maybe this is a separate issue?

Leads me to believe that it's a separate issue.

**Comment by shkm** [comment] 2015-07-16 02:30
Just a little update on my situation: I went back to Neovim today (updated) and everything seems fine. Great work, folks.

**Comment by alerque** [comment] 2015-07-16 03:28
Sadly I'm still running into this. Much less often with python shut off, but we aren't out of tho woods yet.

**Comment by regedarek** [comment] 2015-07-28 14:38
I have the same issue. Here is my stackoverflow question: http://stackoverflow.com/questions/31671376/why-fzf-does-not-work-when-i-open-it-from-vim-intro

**Comment by liujoey** [comment] 2015-08-09 18:45
I had same issue as @cHoco,  select some file from fzf, hit enter to open the file, cursor was not blinking, hit any key closes the buffer.

Few hours later I did `sudo pip install --upgrade neovim`, then boom, the issue is gone.

**Comment by stevendlander** [comment] 2015-09-08 13:28
I am getting this issue with HTML files.  The issue pops up for me when I have a buffer open and try to open a second for the first time.  Once I open a second buffer manually (`:e`) then all the commands work fine for the remainder of the session.

**Comment by tarruda** [comment] 2015-09-18 19:00
can you all check if the bug is still present on master(https://github.com/neovim/neovim/commit/e80d7c0df7ec6e88a964e58d86a70c8f980e4cc1)?

**Comment by kennethlee** [comment] 2015-09-20 00:28
@tarruda Looks good on my end; I haven't experienced any issues thus far. Thanks! :+1:

**Comment by edi9999** [comment] 2015-09-20 08:09
Yes, it seems to work correctly now

**Comment by tarruda** [comment] 2015-09-20 08:14
If anyone still experiences this I will reopen

**Closed by tarruda** 2015-09-20 08:14 UTC
Labels: neovim

**Comment by stevendlander** [comment] 2015-09-21 16:50
Looks good on my end, thank you!
