### ISSUE TITLE
CTRL + R works only after TAB is pressed

### ISSUE THREAD

**Issue by aretor** [junegunn/fzf#1767] opened 2019-11-22 16:29 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (Ubuntu 18.04)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh (v5.4.2)
    - [ ] fish
    
## Problem / Steps to reproduce
Hello! Every time I start my zsh shell, in order to prompt the search for the first time only, I have to do the following:
1) write some text
2) Press TAB to prompt the autocompletion suggestions
3) Press CTRL + R, to prompt the search
If I only do 3) the shortcut doesn't work. After I have done 1) 2) and 3) for the first time I can just do 3) for the subsequent searches. I don't understand what kind of clash there is in the keyboard bindings and how this "autocompletion trick" is able to solve it.
Any help is appreciated, thanks in advance!

**Comment by nitronoid** [comment] 2020-02-28 11:31
Same issue with same OS, using Bash instead of zsh. However I must do this every time I want to search.

**Comment by aretor** [comment] 2020-02-28 11:33
For some reason, the bug disappeared and now CTRL + R works without the TAB trick.

**Comment by LuRsT** [comment] 2020-03-01 17:41
If the bug disappeared, do you mind closing this issue? @nitronoid, could you try it with empty `history` and check if the same thing happens?

**Comment by aretor** [comment] 2020-03-01 17:46
Unfortunately, I am still testifying the bug in other machines, with a similar configuration.

**Comment by nitronoid** [comment] 2020-03-02 10:30
When using CTRL+R I have `--read0` in the search bar, when running with an empty history I have the same, and a new message: `-bash fc: history specification out of range`

**Comment by junegunn** [comment] 2020-03-02 11:58
Please check if the problem is reproducible with a minimal shell configuration.

If you use bash

```sh
git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf

cat > /tmp/fzf.bash << EOF
PATH=/tmp/fzf/bin:$PATH
source /tmp/fzf/shell/key-bindings.bash
source /tmp/fzf/shell/completion.bash
EOF

bash --rcfie /tmp/fzf.bash
```

Or if you use zsh

```sh
git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf

mkdir -p /tmp/fzf-zsh
cat > /tmp/fzf-zsh/.zshrc << EOF
PATH=/tmp/fzf/bin:$PATH
source /tmp/fzf/shell/key-bindings.zsh
source /tmp/fzf/shell/completion.zsh
EOF

ZDOTDIR=/tmp/fzf-zsh zsh
```

If you can't reproduce the problem, it's probably your configuration issue and you'll have to find what's causing the problem.

**Comment by Ruslang** [comment] 2020-03-23 07:13
@aretor this is can help to you https://github.com/junegunn/fzf/issues/1902#issuecomment-602423582

**Closed** 2020-03-23 07:23 UTC
