### ISSUE TITLE
FZF on neovim opens files in rightmost split

### ISSUE THREAD

**Issue by borring** [junegunn/fzf#352] opened 2015-09-21 21:05 UTC
I use vertical splits a lot. FZF is one of the primary methods I use to open files. Unfortunately, on Neovim, if I have a vertical split, FZF always opens the file in the right-most split regardless of which split I have in focus at the time.

This isn't true for regular Vim. It might be because Neovim opens up a new terminal split for FZF, and it's somehow screwing with it.

**Comment by junegunn** [comment] 2015-09-22 01:23
Looks like a duplicate of #348 which I couldn't reproduce.
I guess @azure-satellite knows what should be done.

**Comment by azure-satellite** [comment] 2015-09-22 17:03
In my case it was an autocommand for `BufEnter` which was screwing up stuff. I don't know if this would be true for @borring

**Comment by borring** [comment] 2015-09-22 18:02
Indeed, it was a BufEnter in my case as well.

I had a BufEnter command automatically set the buffer to `buftype=nofile` if no file is open. It also automatically sets `filetype=markdown`

This is because most of the time, when I fire up vim, it's to use for scratch work anyway. I bisected my vimrc and it turns out, it was the `filetype=markdown` that caused the problem. I confirmed it by commenting out the single line.

Replacing BufEnter with BufWinEnter also fixes the issue.

**Comment by azure-satellite** [comment] 2015-09-22 20:13
@borring if this didn't happen in vim perhaps we should investigate further and file a bug with neovim?

**Comment by justinmk** [comment] 2015-09-22 20:48
Please first verify on a _recent_ version of Vim.

**Comment by borring** [comment] 2015-09-24 05:33
I tested with Vim 7.4.854 and it worked as it should. I'm thinking it's because FZF uses the new terminal buffer on Neovim. I reduced my vimrc down to just the relevant bits.

	filetype plugin on
	filetype plugin indent on
	filetype indent on

	" Aesthetics
	set laststatus=2

	" Vim-Plug
	call plug#begin('~/.vim/plugged')

	Plug 'Konfekt/FastFold'
	Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }

	call plug#end()

	" Scratch buffer stuff
	function! IsFile()
		return expand('%') != ""
	endfunction

	function! IsVimInternalBuffer()
		let l:internalbufs = ["quickfix","help","directory","terminal"]
		for i in internalbufs
			if &buftype == i
				return 1
			endif
		endfor
		return 0
	endfunction

	function! SetBuftype()
		if IsVimInternalBuffer()
			return
		endif
		if IsFile()
			set buftype=
		else
			set buftype=nofile
			" It's usually what I want in a scratch buffer anyway
			set filetype=markdown
		endif
	endfunction

	augroup set_buftype
		autocmd!
		autocmd BufEnter * call SetBuftype()
		autocmd BufFilePost * call SetBuftype()
		autocmd BufWritePost * set buftype=
	augroup END

I found that removing the FastFold plugin made FZF work as it should.  Strangely though, FZF is broken on a completely bare nvimrc (for splits).

**Comment by junegunn** [comment] 2015-09-25 02:04
I confirmed that the problem is reproducible with the older versions of Neovim, but not anymore with the latest version with the recent fixes. Please rebuild neovim and try again.

**Comment by borring** [comment] 2015-09-25 03:56
I'm using the latest Neovim from git and still seeing the problem.

Are these the steps you took?

1. Save the nvimrc from this issue
2. nvim -u problem_vimrc
3. :vsplit
4. :FZF (open some file)

**Comment by junegunn** [comment] 2015-09-25 04:34
Ah, sorry I was somehow confused, it's reproducible on the recent build.

However, after a quick look at this FastFold plugin, I now don't think that the problem is something fzf can, or should handle. When the term buffer is closed, fzf uses `wincmd p` to go back to the previous window (note that you can freely move around the windows even after fzf is started), but the FastFold plugin triggered by your `set filetype=markdown` gets in the way, messes up the `p` window. So I would say the problem is in the way FastFold operates, and `BufWinEnter` should be the best way to avoid the problem.

**Closed by junegunn** 2015-09-25 04:34 UTC
Labels: duplicate, neovim
