### ISSUE TITLE
MacVim Lines is slow to jump to target line

### ISSUE THREAD

**Issue by vbrinnel** [junegunn/fzf#1133] opened 2017-11-11 00:43 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Using "Lines" in MacVim is very slow:
 -> I invoke "Lines"
 -> I type the target string I am looking for
 -> I press carriage return on the wished result
 -> MacVim shows immediately the corresponding buffer
 -> But then, I have to wait 5 seconds until the cursor is placed on the right line within the file.

The same procedure performed using vim in a Terminal (either the default Terminal or iTerm2) is fast. 

Best

**Comment by vbrinnel** [comment] 2017-11-11 01:12
Update: it seems to be a redraw issue: if press "Enter" twice, then the cursor is immediately placed one line after the string I was looking for. 

Best

**Comment by junegunn** [comment] 2017-11-12 01:59
Seems like a duplicate of #1103.

**Closed by junegunn** 2017-11-12 01:59 UTC
