### ISSUE TITLE
1 second lag before activation when TERM=xterm-new

### ISSUE THREAD

**Issue by dansanduleac** [junegunn/fzf#1293] opened 2018-05-15 16:53 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

This occurs both in iTerm2 (v3) and Terminal (I'm not using tmux).

Note that setting TERM to `xterm-256color` fixes it, but would like to know why xterm-new causes the lag.

**Comment by svmhdvn** [comment] 2018-09-11 20:55
I just built with commit 8540902 and couldn't reproduce this bug with your configuration, is it still relevant?

environment: macOS 10.13.6, zsh 5.3, Terminal.app

**Comment by junegunn** [comment] 2018-09-12 03:09
I don't know about `xterm-new`, so I can't really answer the question. Please close this if the issue is not reproducible with the latest version, 0.17.4. It was released after you opened this issue.

**Closed** 2020-10-30 14:35 UTC
