### ISSUE TITLE
Conflict with bash-completion: issue with alias

### ISSUE THREAD

**Issue by f3fora** [junegunn/fzf#2583] opened 2021-08-13 20:24 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I  use also `bash-completion`.

Minimal `.bashrc`
```
alias rm='echo "r u sure?"'  # or another random alias

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
```

This works:
```
rm <TAB>
```

This doesn't:
```
\rm <TAB>
```
and raises `bash: warning: programmable_completion: \rm: possible retry loop`

Maybe related to #1227

**Comment by AKSoo** [comment] 2022-01-21 01:41
Duplicate of #2474. Not sure of the owner's opinion, but it seems to be an issue with bash-completion.

**Closed** 2022-07-29 12:51 UTC
