### ISSUE TITLE
fzf-tmux freezes when executed by tmux itself

### ISSUE THREAD

**Issue by jyurek** [junegunn/fzf#2018] opened 2020-05-06 11:56 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When executing the tmux command `run-shell "fzf-tmux"`, the tmux split appears, but then the process filling the tmux options hangs. If the input is small enough, it displays. But if the input is too large (e.g. `fzf-tmux` finding all files), it does not display. And then all keyboard input is ignored, even to the point of being able to unable to control tmux. I have to start a new terminal to `killall fzf` in order to regain control.

Running `fzf-tmux` from the command line inside the shell allows it to operate normally.

**Comment by junegunn** [comment] 2020-05-25 09:59
Duplicate of #1841.

See https://github.com/junegunn/fzf/issues/1841#issuecomment-580975759

**Closed by junegunn** 2020-05-25 09:59 UTC
Labels: duplicate
