### ISSUE TITLE
Keyboard shortcuts don't work unless I explicitly `source ~/.bashrc`

### ISSUE THREAD

**Issue by ptarjan** [junegunn/fzf#716] opened 2016-10-24 21:31 UTC
- Category
  - [ ] fzf binary
  - [ ] fzf-tmux script
  - [X] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ ] Linux
  - [X] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [X] bash
  - [ ] zsh
  - [ ] fish

I did 

```
$ brew install fzf
==> Downloading https://homebrew.bintray.com/bottles/fzf-0.15.5.el_capitan.bottle.tar.gz
Already downloaded: /Users/pt/Library/Caches/Homebrew/fzf-0.15.5.el_capitan.bottle.tar.gz
==> Pouring fzf-0.15.5.el_capitan.bottle.tar.gz
==> Caveats
To install useful keybindings and fuzzy completion:
  /usr/local/opt/fzf/install

To use fzf in Vim, add the following line to your .vimrc:
  set rtp+=/usr/local/opt/fzf
==> Summary
🍺  /usr/local/Cellar/fzf/0.15.5: 17 files, 3.5M
$ /usr/local/opt/fzf/install
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.15.5
Do you want to enable fuzzy auto-completion? ([y]/n)

Do you want to enable key bindings? ([y]/n)


Generate ~/.fzf.bash ... OK
Generate ~/.fzf.zsh ... OK

Do you want to update your shell configuration files? ([y]/n)


Update /Users/pt/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #112

Update /Users/pt/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    - Already exists: line #3

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   source ~/.zshrc   # zsh

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf
```

and then it works great in that window. If I reopen it thought, when I press `CTRL + R` it just puts 

```
$ `__fzf_history__`
```

as my terminal. If I press `Enter` it works and brings up a list, but I select one I get:

```
$ `__fzf_history__`
-bash: !884: command not found
```

The same thing happens for `CTRL + T`.

If I type `source ~/.bashrc` in that same window, now everything works again. Is something you are doing expecting me to `source` bashrc instead of just doing whatever bash normally does?

**Comment by junegunn** [comment] 2016-10-25 04:18
> If I type source ~/.bashrc in that same window, now everything works again. Is something you are doing expecting me to source bashrc instead of just doing whatever bash normally does?

No. If you start a new shell, `~/.bashrc` is automatically loaded, so you don't have to do it manually. Close your terminal emulator completely and restart it and see if it helps.

**Comment by mjwestcott** [comment] 2016-10-25 13:20
On OSX you typically need to source ~/.bashrc from ~/.bash_profile

http://apple.stackexchange.com/a/13019
http://hayne.net/MacDev/Notes/unixFAQ.html#shellStartup

**Comment by ptarjan** [comment] 2016-10-25 18:03
@junegunn yes, that is exactly what is broken. The latter part of my report has 

> If I reopen it thought...

so opening a new terminal is where fzf isn't working.

@mjwestcott I do have that:

```
$ cat ~/.bash_profile
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```

**Comment by junegunn** [comment] 2016-10-26 02:20
What I don't understand about your initial report is

> and then it works great in that window.

It shouldn't, because the code is not yet loaded on the shell. Maybe you missed the step where you `source`d the file? Anyway, I think some other part in your configuration files are interfering with fzf key bindings. Can you post the output of `bind -p`? You should be able to find the following entries:

```
"\er": redraw-current-line
"\e^": history-expand-line
"\e\C-e": shell-expand-line
```

**Comment by paulbersch** [comment] 2016-12-13 19:49
BASH on OSX Sierra (10.12) does not appear to source `~/.bashrc` on startup. I can confirm that adding `source ~/.bashrc` to `~/.bash_profile` resolves this issue.  This could be fixed by either modifying the install script to put `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` in `~/.bash_profile` instead on OSX, or updating the post-install instructions to instruct the user to source the `~/.bashrc` file in their `~/.bash_profile` if it isn't already.

**Comment by junegunn** [comment] 2017-01-07 01:36
@MuschPusch I'm not sure what's going on there. It seems like the bindings from fzf are overridden. Is there any `set` command after the line that loads fzf script?

Excerpt from https://github.com/junegunn/fzf#key-bindings-for-command-line

> If you use vi mode on bash, you need to add `set -o vi` before `source ~/.fzf.bash` in your .bashrc, so that it correctly sets up key bindings for vi mode.

Does this help?

**Comment by MuschPusch** [comment] 2017-01-09 14:46
i source it as last file in my .bash_profile, so no it should be the last one

**Comment by NikosAlexandris** [comment] 2017-02-12 16:08
Last line in `~/.bashrc` is
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

`Ctrl`+`R` returns
```
`__fzf_history__`bash: fzf: command not found
```
and
```
bind -p |grep line |grep [e][r\^]
"\e^": history-expand-line
"\er": redraw-current-line
"\e\C-r": revert-line
```
and the suggestion to `set -o vi` does not work -- in addition it breaks the shell's "normal" behaviour, ie going back in history with the page up/down keys.

**Comment by NikosAlexandris** [comment] 2017-04-25 10:04
Sourcing of `.fzf.bash` works from within `.bash_profile`. Sorry if this issue is only OSX specific. I am on `GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`.

**Comment by junegunn** [comment] 2017-04-25 17:04
@NikosAlexandris Related: https://github.com/junegunn/fzf/issues/282#issuecomment-116651487

**Comment by NikosAlexandris** [comment] 2017-04-26 10:55
@junegunn thanks. I am aware. In fact, I do have the following recommended lines in my `.bash_profile`:
```
# source: http://superuser.com/a/183980/128768
if [ -r ~/.profile ]; then . ~/.profile; fi
case "$-" in *i*) if [ -r ~/.bashrc ]; then . ~/.bashrc; fi;; esac
```

However, for some reason, in my setup, I still have not found, it doesn't work if fzf is sourced from `.bashrc`. Details in my previous posts.

ps- Kudos for the excellent work.

**Comment by jonbarksdale** [comment] 2017-10-22 18:44
For anyone who comes here with a similar problem for zsh, I found that I needed to run the fzf scripts after the completion system initializes, and then it works.  If I ran the fzf stuff first, neither the key bindings or the expansion worked.

**Comment by cevhyruz** [comment] 2018-10-01 03:46
@jonbarksdale solution works for me.. just have to make sure fzf is loaded after the bash_completion.sh file and everythings working again.

**Comment by zwolbers** [comment] 2018-11-19 05:48
Reading through the comments, I suspect different users are seeing slightly different problems, but anyway...  (@MuschPusch I think we're having the same issue.)

Arch Linux/Bash.  Re-sourcing `~/.bashrc` sometimes works for me - it's not consistent for some reason.  Key bindings always work if I'm logged into a virtual console.

I normally have vi mode enabled - I set it in `~/.inputrc`, not `~/.bashrc`.  @junegunn asked if any `set` commands were made after sourcing fzf's scripts - in my case there were not.  I'm beginning to suspect Bash reads `~/.inputrc` last, preventing `key-bindings.bash` from figuring out how to configure itself.

If I also enable vi mode in my `~/.bashrc`, any issues go away.  (I still enable vi mode in my `~/.inputrc` for other programs that use Readline.)

**Comment by tveyben** [comment] 2020-02-17 21:26
> For anyone who comes here with a similar problem for zsh, I found that I needed to run the fzf scripts after the completion system initializes, and then it works. If I ran the fzf stuff first, neither the key bindings or the expansion worked.

In my case (MacOS 10.14.6 with bash 3.2.7) key bindings are not problematic, but expansion did not work until I changed the order as described  by @jonbarksdale!


**Relevant excerpt FROM my .bash_profile:**
```bash
[ -f ~/.fzf.bash ] && source ~/.fzf.bash # <- placed here, **TAB does NOT work as advertised (CTRL+T and CTRL+R does work though)
 # homebrew bash completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash # <- placed here, **TAB DOES work as advertised (CTRL+T and CTRL+R still works)
```

For clarity I tested with the [[ test ]] directly added to `.bash_profile` (as opposed to being sourced from `.bashrc`). The result - naturally - is the same…!

```
tve@TvE-iMac27:~$ bash --version
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

```

 @junegunn asked if any `set` commands were made after sourcing fzf's scripts - also in my case there were none of these.

PS.: fzf = fantastic tool, I am so happy to have discovered it (!)

**Closed** 2020-03-13 12:09 UTC
Labels: not-reproducible
