### ISSUE TITLE
duplicate files when there are circular symlinks

### ISSUE THREAD

**Issue by real-or-random** [junegunn/fzf#1167] opened 2017-11-30 16:01 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

1. `ln -s foo foo`
2. `fzf`, search for something, see duplicate results everywhere

This works also with longer chains of links, e.g., foo -> bar -> foo. Of course, these shouldn't exist in the first place, but they can exist.

**Comment by junegunn** [comment] 2017-11-30 16:32
This is a duplicate of #1120. I'm going to fix this, but for now, you can workaround the problem by setting up a custom $FZF_DEFAULT_COMMAND.

**Comment by junegunn** [comment] 2017-11-30 16:42
Will be fixed in the next release.

**Closed by junegunn** 2017-11-30 16:42 UTC
