### ISSUE TITLE
[neovim] Strange behavior running FZF from a terminal in normal mode.

### ISSUE THREAD

**Issue by atn34** [junegunn/fzf#205] opened 2015-04-20 17:15 UTC
To reproduce:
```
$ nvim
:terminal
<c-\><c-n>
:FZF
<select a file>
press j or k
```
The buffer containing the selected file disappears.

```
$ nvim --version
NVIM 0.0.0-alpha+201504191717 (compiled Apr 20 2015 09:26:01)
Commit: 84891f2802a0db1a257580f341d70a5fdb0f6c75
Build type: RelWithDebInfo
Compilation: /usr/bin/gcc-4.8 -Os -w -pipe -march=core2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150420-21326-qfrz57/build/config -I/tmp/neovim20150420-21326-qfrz57/src -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/tmp/neovim20150420-21326-qfrz57/.deps/usr/include -I/usr/include -I/tmp/neovim20150420-21326-qfrz57/build/src/nvim/auto -I/tmp/neovim20150420-21326-qfrz57/build/include
...
```
```
$ cd ~/.fzf && git rev-parse HEAD
917b1759b08e1105ce964eff23aae8a304a12eee
```

**Comment by junegunn** [comment] 2015-04-20 23:57
Sounds like a neovim issue. Is the problem similar to the one described here?
https://github.com/junegunn/fzf/issues/137#issuecomment-91604555
People have noticed some glitches in neovim terminal when using it with fzf and we'll have to wait until it becomes more stable.

**Comment by atn34** [comment] 2015-04-21 00:20
Yup looks similar, especially the 'If I press any key in this state, the
tab will close' bit, (but in my case it's a buffer). Waiting until neovim's
terminal feature is more stable sounds good to me.

**Comment by jason0x43** [comment] 2015-04-25 16:03
I've been having the same problem for the last week, which also seems to be related to #206. I noticed that opening in a new tab or split seems to always work, while opening in the current window will sometimes show the file and then drop it when a key is pressed, or will show `ml_get` error messages.

My temporary fix has been to use a sink that opens the file or buffer in a new split and then makes that the only split:

	function! s:editfile(filename)
		execute "split " . a:filename
		wincmd o
	endfunction

	function! s:editbuffer(filename)
		split
		execute "buffer " . a:filename
		wincmd o
	endfunction

	command! FZFFiles call fzf#run({
		\'sink' : function("<sid>editfile"),
		\'down' : 8,
		\})

	command! FZFBuffers call fzf#run({
		\'source': s:fzf_buffers,
		\'sink' : function("<sid>editbuffer"),
		\'down' : 8,
		\})

**Comment by jason0x43** [comment] 2015-04-25 17:19
Of course, my suggestion above would need some modification if you generally work with multiple splits, but I don't.

**Comment by jason0x43** [comment] 2015-04-25 17:22
This is a bit more split-friendly:

    function! s:editfile(filename)
        execute "split " . a:filename
        wincmd p
        wincmd q
    endfunction

**Comment by Randuin** [comment] 2015-05-08 04:57
Is there a way to not run FZF through :terminal?

**Comment by junegunn** [comment] 2015-05-08 09:26
@Randuin No. fzf (or any other interactive programs) doesn't work correctly on Neovim without `:terminal`, so it doesn't really make sense to allow it. See #137.

**Comment by Randuin** [comment] 2015-05-13 05:37
So right now I am having an issue that I _think_ is represented by this issue but I think it requires a fix on the neovim side?

The steps to reproduce are 
1. `:FZF`
2. Choose a file
3. `:vsp`
4. `:FZF`
5. Choose another file in the new split
6: The file opens but you still get `--TERMINAL--` at the bottom and if you do anything the file goes away

Is this the issue that I need to wait for neovim to fix?

**Comment by junegunn** [comment] 2015-05-13 16:59
> Is this the issue that I need to wait for neovim to fix?

Yup.

**Comment by junegunn** [comment] 2015-05-13 17:23
Hey guys, could you update the vim plugin and test if it's improved? I simply [added a `redraw!`](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L296) and it seems to help a lot.

**Comment by justinmk** [comment] 2015-05-13 17:38
It helped, but there's still some cases where it closes the result window erronoeously.

**Comment by Randuin** [comment] 2015-05-14 04:36
Seems to fix it for all my usage! Will report back if I run into anything else

**Comment by jason0x43** [comment] 2015-05-28 15:43
It seems to be fixed for me.

**Comment by jebaum** [comment] 2015-09-22 05:24
can't reproduce anymore, this can probably be closed

**Comment by justinmk** [comment] 2015-09-22 05:26
@junegunn The [redraw!](https://github.com/junegunn/fzf/issues/205#issuecomment-101751888) should not be needed anymore.

**Comment by junegunn** [comment] 2015-09-22 07:38
https://github.com/junegunn/fzf/commit/aec48f159b66c0ef3be643741a2cbe99b512aa26

**Closed** 2015-09-22 08:24 UTC
Labels: neovim
