### ISSUE TITLE
Keybinding Issue - Ctrl-r load forever & does not show any results. 

### ISSUE THREAD

**Issue by santi-andracchi** [junegunn/fzf#2013] opened 2020-05-03 18:16 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

After latest Manjaro update, ctrl-R keybindings stops working. It does not show any message at all, its like it is searching forever, since I have to press ctrl-c to kill the process to continue typing in console. Others keybindings does not do anything.

I read key_binding installation and I notice that I have in `/home/<use>/.config/fish/functions/fish_user_key_bindings.fish` the following function:

```javascript
function fish_user_key_bindings 
end

fzf_key_bindings
```

I don't know why fzf is writting that last line outside the function, since in docs and everywhere I check is like this

```javascript
function fish_user_key_bindings 
   fzf_key_bindings
end
```
In spite of this, make it correct does not resolve anything. I update fish and oh my fish also, but nothing. 

I could not found nothing else unusual, and as I said, it was all working perfectly after late SO update

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0
DISTRIB_CODENAME=Lysia

Oh My Fish version 7

fish, version 3.1.1

**Comment by pelmenept** [comment] 2020-05-03 19:14
Same problem here on fish

**Comment by jekanev** [comment] 2020-05-03 20:19
Same fish shell, Arch linux.

**Comment by junegunn** [comment] 2020-05-04 00:58
Duplicate of 2008

**Closed by junegunn** 2020-05-04 00:58 UTC
