### ISSUE TITLE
Use `builtin cd` in fzf Alt+C Key Bindings for Fish Shell

### ISSUE THREAD

**Issue by Undefined01** [junegunn/fzf#3826] opened 2024-05-31 13:46 UTC
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.0 (bcda25a5)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

I'm encountering an issue with the `Alt+C` key binding in the Fish shell when using zoxide, which overrides the cd command. When I activate the Alt+C shortcut, it is not calling the builtin cd because of the alias setup by zoxide, leading to a failure in switching directories.

I think changing [this line](https://github.com/junegunn/fzf/blob/124cd70710cb7c94ef2282773494bb0d727598d8/shell/key-bindings.fish#L96) to `builtin cd -- $result` is sufficient to solve this problem.

This modification is aligned with the implementation in the [Bash script](https://github.com/junegunn/fzf/blob/124cd70710cb7c94ef2282773494bb0d727598d8/shell/key-bindings.bash#L54), where builtin cd is explicitly used to avoid similar conflicts.

**Comment by junegunn** [comment] 2024-06-01 02:33
#3830 should fix the issue. It's in the devel branch, and will be included in the next release.

**Closed by junegunn** 2024-06-01 02:33 UTC

**Comment by harkabeeparolus** [comment] 2024-07-16 06:08
I can't reproduce the bug. I installed the latest version of zoxide, and tried:

```fish
fzf --fish | sed 's/builtin //' > $__fish_config_dir/conf.d/fzf.fish
```

Reloaded fish shell, and then:

```fish
zoxide init fish | source
```

And both `z`, fzf *Alt-C* and Directory History seems to be working.

I was able to break fzf by running an additional `alias cd z`, but this is not the default zoxide behaviour.

**Comment by harkabeeparolus** [comment] 2024-07-16 06:26
Perhaps a good enough fix would be to document that fzf Alt-C in fish is only guaranteed to work if you do not `alias cd` to another command.

And in general, I would recommend `abbr` instead of `alias`. I think many former bash and zsh users are very fond of aliases, but really, in fish it's a lot better to learn to use abbreviations instead, since aliases are actually implemented as functions behind the scenes. So `alias cd z` will actually remove the builtin Directory History function. 😟

**Comment by LangLangBart** [comment] 2024-07-16 06:35
> As far as I can tell, zoxide actually doesn't override the default `cd` command.

```sh
zoxide init --cmd cd fish | source
```

The author of the issue has this setup[^1][^2]

```sh
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init --cmd cd $(__common_rc_get_shell))"
```

```sh
# fish
paria@Paria ~> type -a cd
cd is a function with definition
# Defined via `source`
function cd --wraps=__zoxide_z --description 'alias cd=__zoxide_z'
  __zoxide_z $argv
        
end
cd is a builtin
cd is /usr/bin/cd
```

[^1]: [dotfiles/scripts/function/commonrc.sh at main · Undefined01/dotfiles · GitHub](https://github.com/Undefined01/dotfiles/blob/main/scripts/function/commonrc.sh?plain=1#L56)
[^2]: [ajeetdsouza/zoxide - configuration](https://github.com/ajeetdsouza/zoxide#configuration)

**Comment by harkabeeparolus** [comment] 2024-07-16 06:58
Ah, thanks! That explains it. Using `zoxide init --cmd cd fish` generates the following fish code:

```fish
# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

abbr --erase cd &>/dev/null
alias cd=__zoxide_z

abbr --erase cdi &>/dev/null
alias cdi=__zoxide_zi
```

The underlying issue is caused by zoxide actually being incompatible with the default `cd` command. Regular `cd` can handle the safer syntax `cd -- newdirectory` #2659, but zoxide can not ajeetdsouza/zoxide#332. The zoxide people tried to work around this by modifying fzf #2799, which caused fzf Alt-C to break fish shell's default Directory History and `cd -`.

I would recommend petitioning zoxide to fix their bug: ajeetdsouza/zoxide#332

**Comment by harkabeeparolus** [comment] 2024-07-16 07:33
An alternative strategy, if zoxide is not able to fix their bug for whatever reason, could be to improve the solution from #2659.

Depending on "--" isn't optimal. The best solution is to [prepend filenames with "./" when necessary][fis]:

> [...] if you read in a pathname, as early as possible see if it begins with “-”... if it does, prepend “./”. This eliminates this source of pathnames that are confused as option flags.

 [fis]: https://dwheeler.com/essays/filenames-in-shell.html "Filenames and Pathnames in Shell: How to do it Correctly by David A. Wheeler"

**Comment by LangLangBart** [comment] 2024-07-16 22:08
> The best solution is to [prepend filenames with "./" when necessary](https://dwheeler.com/essays/filenames-in-shell.html#checkdash):

Would you argue for this change, or should there be a `-` check before using `./`?

```diff
--- a/shell/key-bindings.fish
+++ b/shell/key-bindings.fish
@@ -105,5 +105,5 @@ function fzf_key_bindings
 
       if [ -n "$result" ]
-        builtin cd -- $result
+        cd ./$result
 
         # Remove last token from commandline.
```

Applied the patch from above, and it works (only tested on macOS).

```sh
# Create a dummy folder for testing with a leading '-' (dash)
 mkdir -- "-zsh"
# Start minimal Fish environment
command env -i HOME=$HOME TERM=$TERM USER=$USER PATH=$HOME/Developer/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/bin/fish
fzf --version
# 0.54.0 (9e92b6f1)

fzf --fish | source
zoxide init --cmd cd fish | source
# Press 'alt-c' and select '-zsh'
# 'cdh' and 'cd -' work as expected
```

---

Current workaround:
```sh
fzf --fish | sed 's|builtin cd -- |cd -- ./|' | source
```

**Comment by junegunn** [comment] 2024-07-17 03:16
> ```diff
> +        cd ./$result
> ```

This won't work if a custom `FZF_ALT_C_COMMAND` prints absolute paths.

**Comment by LangLangBart** [comment] 2024-07-17 05:59
Checking for a leading dash:

```diff
--- a/shell/key-bindings.fish
+++ b/shell/key-bindings.fish
@@ -105,5 +105,9 @@ function fzf_key_bindings
 
       if [ -n "$result" ]
-        builtin cd -- $result
+        if string match --quiet -- '-*' "$result"
+            cd ./$result
+        else
+            cd $result
+        end
 
         # Remove last token from commandline.
```

**Comment by harkabeeparolus** [comment] 2024-07-17 06:09
That looks good to me! I think this is the best solution. It's as safe as the "--" strategy, while avoiding the bug in zoxide.
