### ISSUE TITLE
Unbounded memory usage

### ISSUE THREAD

**Issue by jonpolak** [junegunn/fzf#656] opened 2016-09-08 21:30 UTC
- Category
  - [X] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [X] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [X] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [X] bash
  - [ ] zsh
  - [ ] fish

**fzf vesion 0.13.5**
**not using tmux**

fzf process ran interminably and memory consumption increased to 8GB and continued to rise until FZF find killed by user.  The command I ran was `vim ~/** <tab>`

The results are shown in these screenshots

![at 2016-09-08 14 11 58]  **\- fzf is consuming 3.9GB out of 20GB of ram** (https://cloud.githubusercontent.com/assets/1812219/18367423/ddd9aaf2-75cf-11e6-822e-17fa5d781928.png)

![at 2016-09-08 14 12 52] - **fzf memory consumption keeps growing.**(https://cloud.githubusercontent.com/assets/1812219/18367463/1e324d8e-75d0-11e6-8215-fa402b440c4f.png)

![2016-09-08 14 14 03] - had to `<ctrl-c>` out of fzf because it was never ending & memory consumption increased without bound.(https://cloud.githubusercontent.com/assets/1812219/18367502/55977b00-75d0-11e6-82f8-6b3e14895a60.png)

I think it has to do with the `-L` passed to find. It is going into a circular reference.

**Comment by junegunn** [comment] 2016-09-11 03:11
Hi, can you provide the steps to reproduce the problem? I couldn't reproduce with the following script.

```sh
mkdir -p /tmp/foo/bar
touch /tmp/foo/bar/baz
ln -s /tmp/foo /tmp/foo/bar/foo

vim /tmp/foo/** <tab>
```

**Comment by jonpolak** [comment] 2016-09-14 20:45
The output of find -L 
```
ind: File system loop detected; ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-1/device/subsystem/devices/i2c-5’ is part of the same file system loop as ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5’.
find: File system loop detected; ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-1/subsystem’ is part of the same file system loop as ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem’.
find: File system loop detected; ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-2/device/i2c-dev/i2c-2’ is part of the same file system loop as ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-2’.
find: File system loop detected; ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-2/device/device’ is part of the same file system loop as ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0’.
find: File system loop detected; ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-2/device/subsystem/devices/i2c-0/i2c-dev/i2c-0/device’ is part of the same file system loop as ‘/home/jojo/PlayOnLinux's virtual drives/pdfTracker/dosdevices/z:/sys/bus/cpu/devices/cpu0/node0/cpu1/driver/cpu2/firmware_node/subsystem/devices/device:00/PNP0800:00/physical_node/subsystem/devices/i8042/serio0/input/input3/event3/subsystem/event10/device/device/device/subsystem/devices/0000:00:02.0/drm/card0/card0-DP-1/subsystem/card0-DP-2/i2c-5/i2c-dev/i2c-5/subsystem/i2c-2/device/subsystem/devices/i2c-0’.

```
continues forever ... and it feeds it to fzf. So the error isn't in fzf it's in find.

**Comment by jonpolak** [comment] 2016-09-14 21:18
Here's [the first 412kB of output](http://pastebin.com/Yjn3jEZN). I let it run for a few seconds and I had about 140M of text output. The issue is this program PlayOnLinux that makes `find -L` go into an infinite loop.

**Comment by junegunn** [comment] 2016-09-18 16:36
You can customize the command used to workaround the issue. See: https://github.com/junegunn/fzf#settings

I'm not sure about removing `-L` from the default command though, I personally like/need the option. Is there any way to avoid the issue without removing `-L`?

**Comment by junegunn** [comment] 2017-06-15 10:05
https://github.com/junegunn/fzf/commit/11407bf65650ef5bd97453e16ab3424b90ef750e

I think this problem should be fixed now as we updated the default command to prune sysfs entries which are showing in your case.

**Closed by junegunn** 2017-06-15 10:05 UTC

**Comment by leaderlessllc** [comment] 2024-12-22 01:10
I encountered this today on latest versions on a 64GB memory M4 Max it brought down the machine to its knees @junegunn are you sure it has been resolved?

**Comment by notpentadactyl** [comment] 2025-02-22 15:09
> I encountered this today on latest versions on a 64GB memory M4 Max it brought down the machine to its knees [@junegunn](https://github.com/junegunn) are you sure it has been resolved?

I encountered this (*or something else?) today on 0.60.0 on a Linux system with 64GB RAM.

My PC was basically frozen, when I connected from a different system with `ssh` I saw all 8c/16t at 100% usage and fzf using all of my memory.

`dmesg` showed many lines like this: `systemd-journald[472]: Under memory pressure, flushing caches.`.

`killall fzf` over `ssh` made the PC usable again.

*I have no idea what I did to trigger this.

**Comment by junegunn** [comment] 2025-02-22 15:26
fzf doesn't limit the input size by default. So if you feed in an unlimited stream of items, the memory usage will continue to grow accordingly. There is `--tail` option to limit the input size, but you normally don't need it.

https://junegunn.github.io/fzf/tips/browsing-log-streams/
