### ISSUE TITLE
Default vim sink doesn't respect working directory

### ISSUE THREAD

**Issue by adigitoleo** [junegunn/fzf#2343] opened 2021-02-03 04:38 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The default 'sink' for `fzf#run()` (vim implementation) is a bit confusing. One might expect that it would give the same result as `'sink': 'e'`, but that's not the case. Using the example from the vim readme:
```
    command! -bang -complete=dir -nargs=* LS
        \ call fzf#run(fzf#wrap('ls', {'source': 'ls', 'dir': <q-args>}, <bang>0))
```
Open vim in directory `A`. Now open a file at some directory, `B`, with `noautochdir`. Then run `:LS` without arguments. Files are listed for `A`, but selecting one with Enter opens an empty buffer with the same name under directory `B`. Adding the explicit `'sink': 'e'` solves this problem, but means losing `<C-t>, <C-v>` etc. actions for opening in splits/tabs.

Is there a reason why the default sink behaves differently to the 'e' command?

EDIT: It appears this only happens when relying on the default sink AND default directory detection. Running e.g. `:LS ~` without specifying the sink also works correctly.

**Comment by adigitoleo** [comment] 2021-02-03 04:44
Slightly off-topic: I recommend changing the examples to use `-nargs=?` since specifying more than one directory argument doesn't make sense (and results in an error).

**Comment by junegunn** [comment] 2021-02-03 04:49
Thanks for the report. I can reproduce the problem.

```
cd /tmp
mkdir -p foo bar
touch foo/1 bar/2

cd foo
vim ../bar/2

#  :command! -bang -complete=dir -nargs=* LS call fzf#run(fzf#wrap('ls', {'source': 'ls', 'dir': <q-args>}, <bang>0))
#  :LS
#    Select 1, opens bar/1, not foo/1
```

This looks like a case where an empty `dir` entry is not properly ignored. This patch should fix the problem.

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index c94bb9e..763747c 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -424,10 +424,10 @@ try
     throw v:exception
   endtry
 
-  if !has_key(dict, 'dir')
+  if !s:present(dict, 'dir')
     let dict.dir = s:fzf_getcwd()
   endif
-  if has('win32unix') && has_key(dict, 'dir')
+  if has('win32unix') && s:present(dict, 'dir')
     let dict.dir = fnamemodify(dict.dir, ':p')
   endif
 
```

**Comment by junegunn** [comment] 2021-02-03 04:51
> I recommend changing the examples to use -nargs=?

Good point. Will do.

**Comment by junegunn** [comment] 2021-02-03 04:53
Should be fixed now. Let me know if you still see the problem. Thanks.

**Closed** 2021-02-03 04:52 UTC
Labels: bug
