### ISSUE TITLE
Clarify what quoting rules are use

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#682] opened 2016-09-28 09:13 UTC
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

IE: the comma in the command are not accepted

--bind "ctrl-m:execute(printf {} | colout '(NAME)*(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' 'red,blue,blue,blue')"
unknown action: execute(printf {} | colout '(NAME)*(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' 'red

IE: $ must be backslashes even when in single quotes in --preview
--preview "perl -e '\$ARGV[0] =~ />>> (.*)$/ ; print \$1' {} "

**Comment by junegunn** [comment] 2016-09-28 09:31
Option parser of fzf uses a simplistic regex to parse key binding expressions. In this case it got confused by the closing parens in the command. We could possibly make the parser more robust, but I don't think it's possible to perfect it so fzf provides workarounds. See "KEY BINDINGS" section of the man page.

You probably want to use `execute:...` syntax.

```sh
# This works fine
fzf --bind "ctrl-m:execute:printf {} | colout '(NAME)(DESCRIPTION)(LONG_)(DEFINED_AT)' 'red,blue,blue,blue'"
```

**Comment by junegunn** [comment] 2016-09-28 09:38
As for the second example, I'm not sure what the problem is?

```sh
# Preview shown only on yes
(echo '>>> yes'; echo '>> no') | fzf --preview "perl -e '\$ARGV[0] =~ />>> (.*)$/ ; print \$1' {}"
```

But things are already hairy with escaping backslashes, I suggest using an external script or function.

```sh
f() { echo ">>> $@ <<<"; }
export -f f
fzf --preview 'f {}'
```

**Closed** 2016-09-29 16:41 UTC
Labels: question
