### ISSUE TITLE
Open FZF in current pane

### ISSUE THREAD

**Issue by jamesgecko** [junegunn/fzf#419] opened 2015-11-13 18:26 UTC
Further discussion of misfiled issue at https://github.com/junegunn/fzf.vim/issues/41, related to #275. The solution described in #275 does not work for me; I'm not sure if the way NeoVim works has changed since then, or if there was additional configuration I'm missing.

I'm using NeoVim, and I want FZF to replace the content of the current split with the selector, then open the selected file in the current split. Here's what I have now:
```
nnoremap <leader>t :call fzf#run({ 'source': 'ag -g ""', 'sink': 'e', 'window': 'enew' })<cr>
```
This opens the selector in the current split, but when the file is selected, FZF closes the split and the file is opened in the next available split. Is there a way to prevent FZF from closing the current split?

**Comment by junegunn** [comment] 2015-11-14 03:10
It works fine for me.

1. Make sure to use the latest nvim release: 0.1.0
2. Try disabling every other plugin you use and see if the problem still persists

**Comment by jamesgecko** [comment] 2015-11-18 16:41
I'm using `NVIM 0.1.0 (compiled Nov  2 2015 11:53:27)` from the homebrew repo.

I've disabled every other plugin but fzf, and the behavior is identical.

**Comment by junegunn** [comment] 2015-11-18 16:46
Anything suspicious in your config? You can try without any other config like follows.
```
# Considering that you installed fzf with vim-plug
nvim -u <(echo 'set rtp+=~/.vim/plugged/fzf')
```

**Comment by jamesgecko** [comment] 2015-11-18 17:42
I use pathogen, so I put the following into `~/miniconfig` and ran `nvim -u ~/miniconfig`

```
execute pathogen#infect()
echo 'set rtp+=/usr/local/Cellar/fzf/HEAD'
let mapleader=","
nnoremap <leader>t :call fzf#run({ 'source': 'ag -g ""', 'sink': 'e', 'window': 'enew' })<cr>
```

No plugins loaded except for fzf, same behavior. FZF is version 0.10.9.

There is an error I've neglected to mention that happens if there's only one pane open:
```
Error detected while processing function 1:
line    5:
E444: Cannot close last window
```

**Comment by junegunn** [comment] 2015-11-18 18:11
Still can't reproduce from my side and no error. Please test again with the following config.

```vim
set rtp+=/usr/local/Cellar/fzf/HEAD
let mapleader=","
nnoremap <leader>t :call fzf#run({ 'source': 'ag -g ""', 'sink': 'e', 'window': 'enew' })<cr>
```

**Comment by jamesgecko** [comment] 2015-12-01 19:33
Upgraded to FZF 0.11.1 and rebuilt my entire config using vim-plug. Somewhere in there it started working properly.

**Comment by junegunn** [comment] 2015-12-01 22:08
Okay. Closing the issue.

**Closed by junegunn** 2015-12-01 22:08 UTC
