### ISSUE TITLE
Why is fzf control t significantly slower when using fd?

### ISSUE THREAD

**Issue by paw-lu** [junegunn/fzf#4089] opened 2024-11-12 00:00 UTC
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

i'm a bit surprised that using `fd` in `FZF_CTRL_T_COMMAND` seems to make fzf control + t much _slower_

https://github.com/user-attachments/assets/41497f89-e917-4a57-a60b-0d4b7ff5e9a8

```console
$ export FZF_CTRL_T_COMMAND=''

$ <control + t>
# instant
  2369/2369 (0) ───────────────

$ export FZF_CTRL_T_COMMAND='fd  --type file --strip-cwd-prefix --hidden'

$ <control + t>
# noticeable lag here

$ fd  --type file --strip-cwd-prefix --hidden | fzf
# running control t command on its own and piping to fzf gives instant results
```

---

sidebar, fzf is an incredible tool, thanks so much for creating, sharing, and maintaining this!

**Comment by junegunn** [comment] 2024-11-15 01:17
I can't reproduce the problem. Are you still experiencing the lag?

**Comment by paw-lu** [comment] 2024-11-16 03:49
huh, yeah I still am. I'll try doing this again on a fresh shell setup to isolate the issue

**Comment by junegunn** [comment] 2024-11-17 10:13
You can try something like `env -i PATH=$PATH bash --noprofile --rcfile <(fzf --bash)`

**Comment by paw-lu** [comment] 2024-11-22 23:38
not able to reproduce on a fresh shell, must be specific to my setup, will keep investigating and report back eventually

**Comment by junegunn** [comment] 2024-11-23 09:07
Thanks, I'll close this for now.

**Closed by junegunn** 2024-11-23 09:07 UTC

**Comment by paw-lu** [comment] 2024-12-06 06:26
ok was able to reproduce it, this was due to the fact that i had a slow running process in my `.zshenv`. 

```zsh
# my zshenv
sleep 10
```

for some reason, this affects the control t command only if we set an alternative `FZF_CTRL_T_COMMAND`.

**Comment by LangLangBart** [comment] 2024-12-06 11:50
> ok was able to reproduce it

Thanks for digging through. I was able to reproduce it as well.

When `FZF_CTRL_T_COMMAND` is set, the command is executed with `$SHELL -c …`, in
your case with `zsh -c …`.


> [!NOTE]
> _The only file you can alter which is started with every zsh (unless you use the -f option) is .zshenv,_
>
> Source: [Z-Shell Frequently-Asked Questions](https://zsh.sourceforge.io/FAQ/zshfaq03.html#l20)

The `.zshenv` file typically includes options, environment variables, and
occasionally small functions[^1], usually without noticeably affecting
performance.


> for some reason, this affects the control t command only if we set an alternative

If you add the `--with-shell 'zsh -fc'`[^2][^3] flag to your `FZF_CTRL_T_OPTS`,
the issue should not occur.


[^1]: [Fzf cannot find a function configured as FZF_ALT_C_COMMAND · Issue #3743 · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/issues/3743)
[^2]: [fzf/CHANGELOG.md 0.51.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0510)
[^3]: If a script altered the `PATH`, it might use a different `zsh` version, so
    it's better to specify the full path, see list below.

    ```bash
    # Depends on whether your 'SHELL' is defined (echo $SHELL).
    --with-shell "$SHELL -fc"

    # Works most of the time, but will return the alias if there is one for 'zsh'.
    --with-shell "$(builtin which zsh) -fc"
    # Same as above.
    --with-shell "$(command -v zsh) -fc"

    # Seems to be the most reliable way to always use your intended 'zsh' version.
    --with-shell "$(command which zsh) -fc"

    # 'zsh' specific, see 'man' pages on the syntax
    # man 1 zshmodules | less -p "THE ZSH/PARAMETER MODULE"
    --with-shell "${commands[zsh]} -fc"
    # man 1 zshexpn | less -p "=' expansion"
    --with-shell "$(printf =zsh) -fc"
    ```

**Comment by paw-lu** [comment] 2024-12-07 00:28
first, this is a fantastic answer, thanks for all the effort here on both the explanation and solution. learned a bit here.

> the command is executed with `$SHELL -c …`

curious, i notice the more files in the directory, the slower this process is. i would intuitively expect a command executed in `$SHELL -c ...` to pay a one time cost in setting up the shell, so it would be equally slow independent on the number of files. but at least observationally it doesn't seem to be the case. full disclosure—my issue is totally solved now from the information you gave me, i'm just curious here.
