### ISSUE TITLE
copy text to fzf input line to search, a little wield.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [junegunn/fzf#961] opened 2017-07-02 10:34 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi, Sometimes i want to copy text to the fzf input line to search file. In iTerm2, when i ctrl+T to invoke fzf and paste with cmd+v, nothing happened, then i press any key, the text will show and the fzf will work.

**Comment by junegunn** [comment] 2017-07-02 11:20
Hi, this is a duplicate of #951. It will be fixed in the next release, but you can build fzf from source now, and it will work fine.

**Closed by junegunn** 2017-07-02 11:20 UTC
