### ISSUE TITLE
[macOS] missing history item with bash 3.2

### ISSUE THREAD

**Issue by step-** [junegunn/fzf#3309] opened 2023-05-25 12:34 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I reproduced this issue on macOS Catalina with bash 3.2, and Linux with bash 3.2. It matters mostly for macOS, in which 3.2 is the default bash version.

On macOS (Linux) the history applet doesn't work correctly with bash 3.2. There are two issues:
* the widget does not list the most-recently typed command;
* the numeric index shown by the widget is off by one.

To reproduce, first add some history and make sure to take the key binding definition from the [source code](https://github.com/junegunn/fzf/blob/d2bde205f0f760f46e87c913450f28bb395b6e11/shell/key-bindings.bash#L82) for bash 3.

```
bash-3.2$ : 1
bash-3.2$ bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
bash-3.2$ <c-r>
...
27	: 1
<esc>
```
You can see that the `bind` command wasn't shown although it should have.
Now run the history widget directly instead of via the `<c-r>` key.

```
bash-3.2$ __fzf_history__
bash-3.2$ bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
...
26	: 1
27	bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
<esc>
```
This time `bind` was there but the widget showed different line numbers!

So the history index shown by `<c-r>` ends up being off by one, which can mislead a user recalling commands with the `!<index>` builtin.
```
bash-3.2$ : 2
bash-3.2$ : 3
bash-3.2$ : 4
bash-3.2$ <c-r>
26	bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
27	__fzf_history__
28	: 2
29	: 3
<esc>
bash-3.2$ !29
: 4
```

You can run similar commands with a more recent bash version -- I happened to have 4.4 -- to find out that this behavior only happens with bash 3.

```
bash-4.4$ : 1
bash-4.4$ bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
bash-4.4$ <c-r>
...
10	: 1
11	bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
<esc>
bash-4.4$ !11
: 1
```

I tested the [builtin fc command](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash#L56) that retrieves history in bash 3.2 and 4.4 on Linux. It outputs identical data in both bash versions for the same history list.

**Comment by junegunn** [comment] 2024-09-01 01:35
Is this still an issue? Can we close this one?

**Comment by step-** [comment] 2024-09-01 05:26
It remains an issue but only with bash 3.2 (macOS Catalina without bash upgrade), and only if the history widget uses perl instead of awk. I would close the issue as "won't fix" due to the limited potential audience and low impact of this issue.

**Comment by junegunn** [comment] 2024-09-01 06:27
Thanks for clarification. I can reproduce the problem, but it happens even when "awk" is used. The problem is `builtin fc -lnr -2147483648` is not reporting the last typed command unlike `history`. I can't come up with a workaround, so I'm going to close this as wontfix as you suggested.

**Closed by junegunn** 2024-09-01 06:27 UTC
