### ISSUE TITLE
CTRL-T shortcut doesn't take FZF_DEFAULT_COMMAND into account

### ISSUE THREAD

**Issue by WishCow** [junegunn/fzf#280] opened 2015-06-25 08:44 UTC
I have set FZF_DEFAULT_COMMAND to ag:
```
export FZF_DEFAULT_COMMAND='ag -l -g ""'
```
And it works as expected when I use the `fzf` command in itself, however if I try to use the (bash) shortcut, CTRL-T, I still see entries that should not be there, eg. files that have been .gitignored.

I looked into the source, and it seems that in `key-bindings.bash`, CTRL-T is bound to the function `__fzf_select__` which has a `find -L ...` hardcoded in it, and it never looks at the FZF_DEFAULT_COMMAND variable.

Is this intentional?

**Comment by casimir** [comment] 2015-06-25 09:55
I have the same behavior with zsh. Didn't find the time to create an issue. :expressionless:

**Comment by junegunn** [comment] 2015-06-25 10:04
Closing as a duplicate of #40.

**Closed by junegunn** 2015-06-25 10:04 UTC
Labels: duplicate

**Comment by junegunn** [comment] 2015-06-25 10:08
In short, we need another variable only for ctrl-t

**Comment by junegunn** [comment] 2015-06-25 16:05
Added `$FZF_CTRL_T_COMMAND` for the purpose.

**Comment by edi9999** [comment] 2015-06-25 20:56
Really ? I don't like having too many config items everywhere, and specifying an env variable specific to one shortcut sounds overkill to me. If somebody wants to change the args of the ctrl-t command, maybe the best would be to just edit the command in the directory itself (or even better, not put the key bindings in the git repository, but rather in the wiki, and people could put those in their bashrc , zshrc and edit them themselves

**Comment by junegunn** [comment] 2015-06-26 01:16
@edi9999 I see your concern, and that's what I would usually tell the users. But we can't ignore that many of the users simply do not want to go that far and `FZF_CTRL_T_COMMAND` seems like an okay compromise to me.

> not put the key bindings in the git repository

You know the install script allows you to opt-out the default key bindings. So it's already an option.

**Comment by edi9999** [comment] 2015-06-26 07:46
Ok, i didn't understand that this was written inside the shell/ code, I thought it would be somewhere in the go code.

That way, concerns are separated and I think it's OK like this
