### ISSUE TITLE
MacVIM Rendering

### ISSUE THREAD

**Issue by jleyser** [junegunn/fzf#1108] opened 2017-10-25 21:03 UTC
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

fzf 0.17.1 (brew), and MacVim 8.0 patches 1-1207

For testing, I've stripped .vimrc down to just:

call plug#begin('~/.vim/plugged')
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

And removed .gvimrc complete

Using vim & FZF from within the terminal works perfectly.  However, if I use GUI mode (i.e. mvim), the rendering of the results pane for FZF gets corrupted.  It appears that the mvim rendering can't "keep up", and it fails to clear some lines, shows color encoded as ESC codes instead of the colors, etc.  Screenshot attached.

I'm guessing this isn't really an FZF problem, but I'm stumped, and can't find anyone else who seems to have this problem.  Is there an FZF setting I'm overlooking that will let mvim 'keep up'?

![mvim-fzf](https://user-images.githubusercontent.com/390910/32022853-782fb262-b98c-11e7-9d72-7d929f25f63f.png)

**Comment by BBonifield** [comment] 2017-10-30 23:22
I've noticed a similar issue, although it doesn't seem to be related to color codes.  It's more like the terminal view has ghosting from previous text:

<img width="752" alt="screen shot 2017-10-30 at 5 21 13 pm" src="https://user-images.githubusercontent.com/182615/32200356-da36b65a-bd96-11e7-9082-3b881e97acda.png">

**Comment by junegunn** [comment] 2017-10-31 09:07
We'll just have to wait until the terminal feature of macvim becomes more stable and reliable.
For the time being, you'll have better experience with GUI versions of Neovim, such as [VimR](https://github.com/qvacua/vimr) which I think is pretty nice (it even has a builtin markdown previewer).

**Comment by BBonifield** [comment] 2017-11-06 19:55
@junegunn Just out of curiosity, do you believe the issue to be specifically related to the terminal feature in MacVim, or do you think it has to do with the fzf renderer?

**Comment by junegunn** [comment] 2017-11-07 00:07
The former, because the rendering is much more stable on the terminal emulator of Neovim.

**Comment by CGamesPlay** [comment] 2017-11-08 19:13
This issue definitely lives in MacVim, you can use the script utility to confirm that the same sequence of bytes results in different results in iTerm2 and MacVim. https://github.com/macvim-dev/macvim/issues/579#issuecomment-342925823

**Comment by yacoob** [comment] 2017-12-31 09:50
Is there a way to disable usage of terminal in the meantime? Judging from https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L394 there doesn't seem to be a user-configurable toggle.

**Comment by yacoob** [comment] 2017-12-31 10:08
Actually, it's not as important, as the alternative (launching a separate iterm) is also ugly. Guess we'll need to wait till `:terminal` gets fixed in Vim8 :(

**Comment by markwu** [comment] 2018-03-13 11:41
I try FZF with VIM today, all works well. Except terminal rendering problem. Now, I know what's going on.

**Comment by CGamesPlay** [comment] 2018-03-13 17:33
I haven't dug into this issue in any more depth (nor have I ever opened the source code for MacVim or fzf, so I'm by no means an expert here), but what I've noticed from living with this issue daily is:

- The output is mangled, but the darkened line of the current selection is generally right, so you can kinda scroll through the items and choose the right one.
- The issue seems to be timing related, because typing too quickly will cause output to get put into the input stream. You may need to backspace over the invalid input to correctly locate your file.

**Comment by CGamesPlay** [comment] 2018-03-22 19:57
Fixed in MacVim https://github.com/macvim-dev/macvim/pull/651

**Comment by statico** [comment] 2018-03-25 22:52
Confirmed. FZF works great in MacVim as of Snapshot 146. Thank you @ichizok and @splhack!

**Closed** 2018-04-05 08:58 UTC
Labels: help-needed
