### ISSUE TITLE
AVG reports Win32:Malware-gen

### ISSUE THREAD

**Issue by frankyuan** [junegunn/fzf#2065] opened 2020-05-31 14:31 UTC
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
* Install AVG Business (software version 20.3.3120, Virus definitions version: 200530-0)
* Install fzf plugin for gvim, after type `:files!`,  there is a message "fzf executable not found. Download birary?", choose `y`.
* fzf.exe is in quarantine. Threat name: "Win32:Malware-gen"

**Comment by jafin** [comment] 2020-05-31 22:03
Similar error just occured with MalwareBytes (Windows)  
```
Generic.Malware/Suspicious, C:\PROGRAMDATA\CHOCOLATEY\LIB\FZF\FZF.NUPKG
```

**Comment by junegunn** [comment] 2020-06-01 02:41
Duplicate of #2002

**Closed by junegunn** 2020-06-01 02:41 UTC
