### ISSUE TITLE
Cannot execute neovim, vim and less via bind when fuzzy completion

### ISSUE THREAD

**Issue by yanzhang0219** [junegunn/fzf#2046] opened 2020-05-18 06:53 UTC
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Set `FZF_DEFAULT_OPTS` to:
```
export FZF_DEFAULT_OPTS="--bind 'ctrl-v:execute(nvim {})'"
```

Then we launch fzf by fuzzy completion, i.e., `fzf ~/.config/**<TAB>`. Next, we search an existing file say `test.txt`. Then on this file we type `CTRL-v` to open this file via neovim. But the terminal becomes blank and neovim cannot be open. Screenshots are shown below.

![image](https://user-images.githubusercontent.com/11582667/82182143-a346d280-9898-11ea-8d07-b9aea1e4a8e9.png)

After I type `CTRL-v`:
![image](https://user-images.githubusercontent.com/11582667/82182185-b5c10c00-9898-11ea-9972-c3ccca0acd29.png)

Next, I tried to run nvim in debug mode by `--bind 'ctrl-v:execute(nvim -V {})'`. It is stuck like below:
![image](https://user-images.githubusercontent.com/11582667/82182363-0a648700-9899-11ea-88a7-95d17366856c.png)

However, if I run fzf directly without fuzzy completion, i.e., `fzf`. Then in fzf, I search `.config/test.txt` and type `CTRL-v` on it, nvim can be launched successfully. 

What's more, instead of launching neovim, I have tried vim and it was stuck there as well like the screenshot below
![image](https://user-images.githubusercontent.com/11582667/82182865-d0e04b80-9899-11ea-8a66-8c4601473f6c.png)

How can I solve this issue so that I can open nvim in fuzzy completion? Thank you very much. 

EDIT: Except for neovim and vim, I just now tried `less` by `--bind 'ctrl-v:execute(less {})'` and it didn't work either. It seems that all programs which should be open and run in the terminal do not work.

**Comment by junegunn** [comment] 2020-05-25 10:04
Duplicate of #1593. See https://github.com/junegunn/fzf/issues/1593#issuecomment-498007983

**Closed by junegunn** 2020-05-25 10:04 UTC

**Comment by yanzhang0219** [comment] 2020-05-25 16:34
Thank you.

I have a confusion. I set `--bind 'ctrl-v:execute(vim {}) first. When running fzf normally like just typing `fzf`, ctrl-v on a target will open it via vim successfully. But if I run fzf by `fzf ~/.config/zsh/**<TAB>`, ctrl-v on a target to open it via vim will fail. I am so confused. Why the later one needs to set the redirection of STDIN and STDOUT to /dev/tty but the former one doesn't? Thanks.
