### ISSUE TITLE
Keybinding variants for [A-Z]

### ISSUE THREAD

**Issue by mkoskar** [junegunn/fzf#1467] opened 2019-01-02 14:31 UTC
- Category
    - [x] Key bindings
- OS
    - [x] Linux

Defining binding for `alt-J` is the same as for `alt-j` reacting on `^[j`. Why don't have it work for `^[J` as is usually expected?

**Comment by junegunn** [comment] 2019-02-03 05:19
Duplicate of #1404.

**Closed by junegunn** 2019-02-03 05:19 UTC
