### ISSUE TITLE
Reverse history search yields a single line with all commands in history

### ISSUE THREAD

**Issue by Elkasitu** [junegunn/fzf#2118] opened 2020-07-22 10:11 UTC
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Problem:

I recently updated fzf (i rarely do this) and now whenever I do a reverse history lookup all the commands of my history are bundled into a single line and I cannot choose a single command individually (fzf will try to call all commands at once, which fails)

![2020-07-22-115647_888x95_scrot](https://user-images.githubusercontent.com/4931545/88163686-57efce00-cc13-11ea-8811-bb3ad229f742.png)

Steps to reproduce:
- Press Ctrl-r to bring up history reverse search

Additional information:
I did a git bisect and found #1837 to be the "culprit", not sure if it's actually the culprit because other things may have had an effect (such as bash version which is 5.0.17(1)-release on arch linux) but in any case 1ccd8f6a647a31f8cb1d683d25d9f21ab28b11cc is the last working revision on my machine.

I applied the following patch locally which works but I doubt it's the correct fix

```diff
diff --git a/shell/key-bindings.bash b/shell/key-bindings.bash
index e157b07..9bee49e 100644
--- a/shell/key-bindings.bash
+++ b/shell/key-bindings.bash
@@ -48,7 +48,7 @@ __fzf_history__() {
   local output
   output=$(
     builtin fc -lnr -2147483648 |
-      last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |
+      last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_\n" if !$seen{$_}++' |
       FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m --read0" $(__fzfcmd) --query "$READLINE_LINE"
   ) || return
   READLINE_LINE=${output#*$'\t'}
```

this is the result after applying the patch
![2020-07-22-115723_435x190_scrot](https://user-images.githubusercontent.com/4931545/88164286-3a6f3400-cc14-11ea-88d8-b883fb1e6e68.png)

however it obviously breaks multi-line commands (or at the very least, makes them look weird)
![2020-07-22-115745_423x184_scrot](https://user-images.githubusercontent.com/4931545/88164352-4c50d700-cc14-11ea-86e8-adcd06fb60ef.png)

**Comment by junegunn** [comment] 2020-10-23 16:07
Closing as I can't reproduce the problem.

![image](https://user-images.githubusercontent.com/700826/97027034-27faf280-1595-11eb-89b7-045777983528.png)

![image](https://user-images.githubusercontent.com/700826/97027051-2df0d380-1595-11eb-98fa-85ec34a70b3a.png)

**Closed by junegunn** 2020-10-23 16:07 UTC
Labels: not-reproducible

**Comment by Elkasitu** [comment] 2021-03-01 09:07
I ran into this problem again recently (because I updated FZF), @junegunn is there something I could to aid in reproducing this issue? maybe share my `.bashrc` or the terminal emulator that I use? ([kitty](https://github.com/kovidgoyal/kitty))

**Comment by adamsanghera** [comment] 2021-09-13 21:48
fwiw, I've encountered this problem, too, on macs and linux boxes.
My guess is that it has something to do with with my bash or perl settings.
Elkasitu's patch has worked for me.

If there's any diagnostic information I can provide to be of use, I'd happy to give it.

**Comment by Elkasitu** [comment] 2021-09-14 06:55
Could you confirm that  1ccd8f6 was the last working revision for you? I recently had to set up a new machine and still had the same problem

**Comment by junegunn** [comment] 2021-09-15 02:51
We started using `perl` in #1837. So it's probably related to your perl version? Which version of perl is installed in your system?

**Comment by Elkasitu** [comment] 2021-09-15 06:34
`This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi`

**Comment by bukowa** [comment] 2025-06-05 23:49
Happens for me since `0.61` - last working version is `0.60.3 (0012183e)` (git bash from git for windows)
https://github.com/junegunn/fzf/compare/v0.60.3...v0.61.0

```
$ uname -a
MINGW64_NT-10.0-19045 DESKTOP-BRET1OM 3.5.7-463ebcdc.x86_64 2025-03-03 17:26 UTC x86_64 Msys
```
```
$ bash --version
GNU bash, version 5.2.37(1)-release (x86_64-pc-msys)
```

```
$ perl --version

This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-msys-thread-multi
```
