### ISSUE TITLE
[Feature Request] Add ability to execute selection in current shell. 

### ISSUE THREAD

**Issue by piersy** [junegunn/fzf#1552] opened 2019-04-11 13:41 UTC
Often when I am using the `ctrl-r` functionality of fzf I would like to be able to execute the selected command directly in my shell with a single button press. I have looked into using execute but unfortunately execute runs the provided command in a subshell, meaning that entries such as `source ~/.zshrc` don't work as expected.

I know that If I turn off paste bracketing, then newlines in pasted input cause the previous input to be executed. So I was wondering if adding a newline to the end of the selection could work, or I was thinking fzf could add a new return code that would allow the widgets to understand that they should execute the command rather than insert it into the commandline.

**Comment by simonfxr** [comment] 2019-06-05 07:21
I really would like to do that also. I found work arounds for fish and bash, such that a command is run immediately. Ideally I would like to have a keybinding in selection mode, where return inserts and runs the command and another keybinding (say `ctrl-i`) just pastes it without running. 
Here are my workarounds:
In bash you can just add a '\n' to the end of the bind:
```sh
bind '"\C-r": " \C-e\C-u\C-y\ey\C-u`__fzf_history__`\e\C-e\er\e^\n"'
```
fish:
```fish
function __sfx_fzf_reverse_isearch
    __fzf_reverse_isearch
    commandline -f execute
end

bind \cr '__sfx_fzf_reverse_isearch'
```

**Comment by iiey** [comment] 2019-07-12 10:01
IMHO it's not belong to fzf new feature.

Did you look into ``--expect``?
```
mapfile -t out < <(.. fzf... --expect=ctrl-x)
key="${out[0]}"
cmd="${out[1]}"
[ -n "$key" ] &&
case "$key" in
        ctrl-x) eval "$cmd" ;;
esac
```
But the tricky part is how to construct builtin ``bind`` to handle output because binding ``$(cmd)\e\C-e`` takes output of ``cmd`` and insert in command line -> It will be a mess if cmd has multiple output lines.
I still not figure out how to have both behaviours in one ``ctrl-r``:
1. Press ``enter``: return selected command in command line so we can modify it before execution
2. Press ``ctrl-x``: execute selected command and return it's output

**Comment by junegunn** [comment] 2019-08-06 04:49
Duplicate of #1492

**Closed by junegunn** 2019-08-06 04:49 UTC
