### ISSUE TITLE
Directly execute item from history

### ISSUE THREAD

**Issue by paulmenzel** [junegunn/fzf#696] opened 2016-10-06 20:45 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Having switched to fzf, and coming from the normal Bash backwards history search, it’d be great, if selecting the item from the fzf list, would execute it right away, so I only have to hit return once.

**Comment by junegunn** [comment] 2016-10-08 18:57
Duplicate of #477. The issue is left open as we haven't found a way to allow the user to dynamically choose which action to perform, edit or execute, on bash. If you unconditionllay want to execute the command, you can simply append `\C-m`  to the key binding.

```sh
# Append \C-m
bind "$(bind -s | grep '^"\\C-r"' | grep -v '\\C-m' | sed 's/"$/\\C-m"/')"
```

Alternatively, you can define an extra key binding for that leaving the default one unchanged.

```sh
# CTRL-X CTRL-R
bind "$(bind -s | grep '^"\\C-r"' | sed 's/"/"\\C-x/' | sed 's/"$/\\C-m"/')"
```

**Closed by junegunn** 2016-10-08 18:57 UTC

**Comment by fgervais** [comment] 2018-07-17 14:39
I added the "Append \C-m" line to the end of 

`shell/key-bindings.bash`

It works but is this the correct location?
