### ISSUE TITLE
selector results leak into preview

### ISSUE THREAD

**Issue by unmellow** [junegunn/fzf#2372] opened 2021-02-27 20:23 UTC
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
on an manjaro
run  
```sh
expac -S "%-33n\t%d" | fzf --preview 'echo text'  
```
and search for ion
scrolling will extend the damage

I can't tell exactly what causes it but it only seems to
happen when the description of the packages listed
is longer than selector line but only by a specific amount
examples:
![2021-02-27T15:08:59,534973716-05:00](https://user-images.githubusercontent.com/30985587/109398937-be596f00-790d-11eb-86a7-531d145b2a00.png)
![2021-02-27T15:08:46,271081580-05:00](https://user-images.githubusercontent.com/30985587/109398938-be596f00-790d-11eb-9c00-974fded985f2.png)
![2021-02-27T15:11:28,479995050-05:00](https://user-images.githubusercontent.com/30985587/109398998-17290780-790e-11eb-9b56-52af1a39e5f1.png)

also fzf seems to make weird decisions regarding layout in general
example
![2021-02-27T15:20:22,012124221-05:00](https://user-images.githubusercontent.com/30985587/109399215-7d625a00-790f-11eb-91b6-e652ce6a817c.png)
![2021-02-27T15:20:36,964053681-05:00](https://user-images.githubusercontent.com/30985587/109399214-7d625a00-790f-11eb-9891-945b4917d7d3.png)

**Comment by unmellow** [comment] 2021-03-01 21:19
@ excalibur1234 found the cause of the issue here: https://github.com/excalibur1234/pacui/issues/61

"it seems the tab (i.e. "\t" in the printf statement) symbol causes this bug."

**Comment by junegunn** [comment] 2021-03-06 07:59
Can you post the output of `expac -S "%-33n\t%d"` as an attachment file here?

**Comment by unmellow** [comment] 2021-03-11 23:08
https://gist.github.com/unmellow/19a27694e8d7a03782d9ee64113ffcc6
here you go

**Comment by junegunn** [comment] 2021-03-11 23:36
Turns out this is a regression caused by #2258.

**Comment by junegunn** [comment] 2021-03-12 01:08
It should be fixed now, thanks for the report.

**Closed** 2021-03-12 01:08 UTC
Labels: bug
