### ISSUE TITLE
Custom selected character

### ISSUE THREAD

**Issue by wayneashleyberry** [junegunn/fzf#692] opened 2016-10-04 08:38 UTC
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

There's an option to customise the prompt character, but the same character is used to highlight the selected result. It would be great to have an option to customise that character as well, to use something like `→` or `⇢` etc.

Here's a little example:

```sh
  github.com/foo/bar
⇢ github.com/baz
  github.com
  3/3
$ github
```

I think this is where it's hardcoded:

https://github.com/junegunn/fzf/blob/master/src/terminal.go#L629
https://github.com/junegunn/fzf/blob/master/src/terminal.go#L636

If this would be a valid option to add then I could try and send a pull request?

**Comment by junegunn** [comment] 2016-10-04 16:16
The idea was suggested in the past, but I declined. And I'm still not sure if I want this.

The problem is not that it's hard to implement – it's quite the opposite as you might have guessed – but that I do not want fzf to end up with a bunch of options for tweaking minor UI elements. Imagine, `--inline-info-separator`, `--info-format`, `--gutter-width`, `--border-style`, `--preview-padding`, the list goes on, and there's no reason that we should offer one but not the other. I don't think I want to go that direction.

One can argue that we already have `--prompt` in that family, but the way I see it is that the main purpose of `--prompt` is to indicate the context of the search (e.g. `fzf --prompt $(pwd)/`). So it's not just for changing the style of an element.

I may revisit the idea later, but for now I'll close this as wontfix. Thanks for the suggestion.

**Closed by junegunn** 2016-10-04 16:16 UTC

**Comment by wayneashleyberry** [comment] 2016-10-04 16:42
Fair point, I completely understand your viewpoint @junegunn - thank you for explaining and thank you for an incredible tool!

**Comment by junegunn** [comment] 2016-10-04 16:45
No problem, thanks for understanding.
